### ISSUE TITLE
Reverse fstring documentation

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#127]
When users indicate they'd like to use path expansion to discover subjects / sessions, we need to provide documentation of how this works.

This can quickly be done on the GUIDE end by replicating the component shown below (from guided/start):
![Screenshot 2023-04-17 at 11 51 15 AM](https://user-images.githubusercontent.com/46533749/232583028-878109e4-5b88-4cea-adc5-66cc4359f8a8.png)

However, we'll want to (1) provide a short description inside the box, or (2) create an extensive demo that we link to.

**Comment by CodyCBakerPhD** [comment]
This has now been vastly expanded upon
