### ISSUE TITLE
Improve the presentation of conditional properties as an OR

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#128]
Instead of simply rendering the inputs for conditional requirements together, we should instead break the panel into two sides: the first with a radio button where users indicate the property they'll specify, and the second which renders the input for that property.

**Comment by CodyCBakerPhD** [comment]
Was this done at some point? I'm thinking #121?

**Comment by garrettmflynn** [comment]
No these are still fully enumerated at this point

**Comment by CodyCBakerPhD** [comment]
Oh I see, so they select whether they want to input age OR date of birth and it only renders the one

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Would you say this has been resolved by now?

**Comment by garrettmflynn** [comment]
Not in the way that this requests. Though it may no longer be something we want to attend to given the updates to the Inspector message (https://github.com/NeurodataWithoutBorders/nwbinspector/pull/411)
