### ISSUE TITLE
Hot Reload Electron on Python Changes

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#136]
While testing #133, we had discussed the utility of adding Python scripts to the watch list so that the backend will reload when changes are detected.

As noted by Cody:
> It could act as a really convenient way of doing certain dynamic imports/installs going into the future

Is this something we'd like to pursue? It will require a custom watch system built with `chokidar`—though this will not be too complicated.

**Comment by CodyCBakerPhD** [comment]
I think this works now, right? @garrettmflynn

**Comment by garrettmflynn** [comment]
Yep! This can be closed, thanks for going through these
