### ISSUE TITLE
Add issue forms

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#164]
And improve the fields, being consistent with PyNWB and the Inspector

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Is this complete or did we want to add additional templates?

**Comment by CodyCBakerPhD** [comment]
I'd add a [config file](https://github.com/catalystneuro/neuroconv/blob/main/.github/ISSUE_TEMPLATE/config.yml) pointing to general NWB stuff as well as link to request format support on NeuroConv

Also probably agreement to follow code of conduct and all that
