### ISSUE TITLE
[MVP] Increase tests of MVP-related functionality

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#167]
With both pytest unit tests of the API/manager, as well as vitetest for front-end components.

Also add more stories as examples if necessary for checking UI rendering

#111 will help quite a bit with this too by helping us identify any gaps

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD Think we can close this out with all the new tests we've added over the last year? Just thought I'd do a thorough review of the open issues.

**Comment by CodyCBakerPhD** [comment]
I would consider it closed once coverage is above 90%

**Comment by garrettmflynn** [comment]
Ah good point. Thanks for clarifying

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn With the e2e tests comfortable in (though I understand they might not be able to help directly) this is now priority again over the next month or so

Shooting for 90% coverage if possible

Looks like a huge number of lines tracked at the lottie assets? But I assume those wouldn't factor to vitetests, so fine to perhaps just set them to ignore?

https://app.codecov.io/github/NeurodataWithoutBorders/nwb-guide/tree/main/src%2Frenderer
