### ISSUE TITLE
[Documentation] Add section on how to access and use swagger version of the API calls

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#168]

**Comment by garrettmflynn** [comment]
If we'd like anyone to be able to play around with the commands, that implies that (1) we'd have a version of the Flask server running in the cloud and (2) writing your own commands to this server, whether cloud-based or local, would actually be desirable. Is that something we'd want to do moving forward?

Alternatively, we could expose the Swagger page of an active GUIDE application as an iframe on the Documentation page or elsewhere. Though this still presupposes some utility to this inclusion of the API docs.

**Comment by CodyCBakerPhD** [comment]
This for sending/receiving API calls to a local host server outside of the main front-end

**Comment by CodyCBakerPhD** [comment]
Mostly for us as developers to understand what is exposed
