### ISSUE TITLE
[Idea] File selector, by default, only looks for 'valid' files

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#170]
For the source data selection step for each interface, we usually know what the supported or common file suffixes are for that format (if a file based format) and likewise the folder structure required by the interface if it's a folder-based format

So it would be cool if the file selector, when pointed to a large folder with a bunch of files, filtered out all the ones not one of the designated suffixes

This would require a small addition to NeuroConv to actually write down that suffix relationship as a class attribute on each interface, similar to how we handle keywords right now

**Comment by bendichter** [comment]
Good idea. See also the python-neo extensions: https://github.com/NeuralEnsemble/python-neo/blob/d07a47b6537d06f7695c382c2bc81d6be5e50df9/neo/rawio/spikeglxrawio.py#L73

**Comment by garrettmflynn** [comment]
We've started approaching this in NeuroConv (https://github.com/catalystneuro/neuroconv/pull/734) and have included partial support in an open PR (https://github.com/NeurodataWithoutBorders/nwb-guide/pull/589).

We'll add the ability to filter some of the options available in the native file selector in an upcoming PR.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn I think this can be closed now right?

**Comment by garrettmflynn** [comment]
Just opened a PR to actually filter file options!
