### ISSUE TITLE
[Idea] Import/Export project for sharing

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#173]
A single user might need to change work stations during the GUIDE conversion process

Likewise, data scientists for a U19 (or from CN) might want to develop a preconfigured pipeline for someone else to run

It would be cool if there was a mechanism for exporting an existing pipeline so they don't waste time redeveloping it, and then importing it from a separate instance of the GUIDE

I'm sure this is quite easy since the files are there somewhere underneath the application; I know the user could technically achieve this by copying and pasting those files into the right directories in each system, but I also assume it would be easy to add convenient buttons for this to the app itself

**Comment by garrettmflynn** [comment]
Just adding a few more notes here. After adding this feature, it will be relevant to:
1. Distinguish between Completed and Ongoing conversions
2. Block users from visiting pages other than the DANDI Upload and Conversion Report pages after running a full conversion once
