### ISSUE TITLE
[Post-v1.0] Easy way to add custom attributes to file (via lab metadata extension)

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#178]
This one I leave to @rly ; basically, users often want to add all kinds of custom lab-specific experiment/subject metadata to the files

Would be cool if this could reduce to a couple of simple buttons in the app that then generate a specific extension on the fly

Or outside of 'guided mode' there could be a free-form mode (like from SODA) where one of the modes is 'create an extension' in which case the main 'guided mode' would need a button for 'import a metadata extension' or something like that

We can hash out specific implementation details later, just starting this issue for now

**Comment by bendichter** [comment]
This would be cool! As a first, pass,iIt might be useful to dynamically generate a webform using the JSON  schema for the NWB schema language: https://github.com/NeurodataWithoutBorders/nwb-schema-language/blob/main/source/nwb.schema.json

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/847

Re-open again whenever this starts active development
