### ISSUE TITLE
Should default value for `subject.sex` selectors be blank?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#179]
I'd say that the default value for each `subject.sex` dropdown should start off as 'Select an option' (or just blank, an empty string) so that we are never assuming the sex and we always actually require the user to select an option there

It is this way on the first encounter with the field under the project level metadata

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/beec4c0e-5b2b-4c89-80a4-758c60117253)

but then on the session manager table it becomes 'U'

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/689bedd6-8518-4298-9395-49f2e4fd4b1a)

This also then occurs during session-level metadata entry even though 'Select an option' is in the dropdown

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/7aa60921-3ee0-43f5-8481-ba73ba0ce3f5)

**Comment by garrettmflynn** [comment]
Closed via #280
