### ISSUE TITLE
[Bug] Dragger for drag-and-drop is no longer working

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#180]
Just noticed this now

Probably really hard to add a test for I'm guessing

https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/ec8f644a-90a2-4253-ad81-1490a2bbf430

**Comment by garrettmflynn** [comment]
This also works on my PC. Looks like this might have something to do with your system—though I'm not sure what that would be.

**Comment by garrettmflynn** [comment]
Any chance you can tell if you were running the application in Administrator Mode (https://github.com/electron/electron/issues/12460#issuecomment-421806991)?

**Comment by CodyCBakerPhD** [comment]
I usually need to run in admin mode anyhow to save files through the app - I assume I would have therefore been doing that back when I first detected the issue but maybe not

Anyway I can't replicate this any more (seems to be working fine) so I'll close and re-open if I see it again

**Comment by johnmbarrett** [comment]
This bug appears to be regressed in version 1.0.7. See below GIF. This is a fresh current-user-only install on Windows 11, all I did was create a pipeline and try to add OpenEphys as a data source. Click to choose a folder seems to work fine. Please let me know if there's any other system info you need to help diagnose.

![Image](https://github.com/user-attachments/assets/3f374224-640d-4de7-a5f7-1eefaa306fe8)

**Comment by rly** [comment]
Thanks for the bug report @johnmbarrett . We'll look into this. Please continue to use the choose a folder / popup file selector in the meantime.
