### ISSUE TITLE
[Idea] Better file content previews

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#185]
The current behavior is fine for MVP (essentially a dump of what you get from calling `print` on an NWB file in-memory)

But @garrettmflynn mentioned it might not be that hard to run NWB Widgets or WebNWB visualizations on a stubbed NWB file directly through the app

I know many users would greatly appreciate this, since they often think of their data not in the way that it's stored in the file but how it is rendered by visualization software (especially for microscopy data)

Would also give a good early indicator of temporal alignment via PSTH's (for sorting data anyway)

**Comment by garrettmflynn** [comment]
Just started experimenting with rendering NWB Widgets on the browser on the `visualize-with-widgets` branch. Based on discussions with Ben and others, I tried using (1) PyScript / Pyodide as well as (2) `voila`—but came up short using both methods. 

## Pyscript
`pyscript` is very particular to inconsistent dependencies and requires you to specify a `*py3-none-any.whl` file for dependencies you'd like to pre-resolve. This allowed me to fix an issue with `numpy` brought on by `ruamel.yaml`—though I wasn't able to resolve a similar problem for `multidict` from `nwbwidgets`. 

Based on this, I was not able to run NWB Widgets or stream a file using `ffspec`. However, I was able to fix Oliver's original demo and print out the string representation of a remote file.

## Voila
`voila` is very close to working—though rendering hangs for properties other than `file_create_date` and `subject`. No errors are thrown.

The original notebook can render all other properties when accessed via VS Code, so the code appears to be functional.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn  At a minimum, can we leverage the new HTML repr capabilities of NWBFiles instead of the pure-text printout?

**Comment by garrettmflynn** [comment]
Just added the HTML representation capacity in #233

**Comment by CodyCBakerPhD** [comment]
I saw, testing it out now (also appended to name of the base PR)

**Comment by CodyCBakerPhD** [comment]
Closed by #232
