### ISSUE TITLE
Improved Table Interactions

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#190]
## SimpleTable Improvements
While these improvements would make the `SimpleTable` component more viable to use, they are not critical path for the MVP and the general generation of tables from JSON Schema:
1. Faster initial render time for interactive table
   - Add rows until one is not visible. Once that is visible, add the next. Keep monitoring column td elements for visibility.
2. Add named columns. 
   - Will require some sort of pop-up for all metadata
3. Copy-paste not working…and, specifically, no copying on Windows
4. Right-click does not allow you to copy
5. Implement a datetime selector
6. Implement a dropdown

**Comment by CodyCBakerPhD** [comment]
And the `SimpleTable` was already, before these proposals, faster than `HandsOnTable` for > 30 rows right?

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Should we close?
