### ISSUE TITLE
[Idea] Render Fields as Tabs in JSONSchemaForm rather than Accordions

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#191]
This update would allow for the visualization of top-level properties (e.g. NWBFile, Subject, Ecephys) as a set of tabs that the user could swap between.

In some previous discussions, we thought this might be more ergonomic than the current Accordion component that often extends far beyond the bottom of the instance manager and doesn't allow for easily swapping between categories.

**Comment by CodyCBakerPhD** [comment]
Thanks for remembering this one - I had forgotten to write it down 👍

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
