### ISSUE TITLE
[Idea] Link session ID (and possibly other fields) across pages

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#201]
From the conversation of https://github.com/NeurodataWithoutBorders/nwb-guide/pull/198#issuecomment-1555331298

> As I've been interpreting it, the sessions property is an unordered list of the sessions that a particular subject has available.

Correct; this understanding and the mapping from the main session manager (subject table) is fine

> In other words, a session's metadata will be cleared if its entry is removed from the list. I thought this was the most elegant way of handling this input's behavior.

As a principle of design, I believe we should avoid situations in which a user is allowed to enter information (in this case, potentially quite a lot of information) and then without warning cause a complete loss of that information

Even if we wanted to keep the behavior of wiping form data upon session ID change from the session manager page, it should at least give some big warnings and ask for confirmation, letting the user know they risk losing inputs

I'd prefer to avoid the situation altogether though, and have an idea introduced below for how I prefer to think about it

> Do you want to generally maintain some understanding of the position of the session in the list and attach metadata to that rather than the actual session_id?

Position does not matter, it's always an unordered list

What I envision is rather than that the value of the session ID as specified on the session manager page is not only the default of the NWBFile metadata form, but that they are the same property under-the-hood, so that changes in one place occur in the other

How complicated would it be to implement something like that? The same idea might apply to all information on that table now that I think about it

But this would help resolve those 'merge resolution' problems you had hypothesized might happen by keeping them in-sync with each other

> It seems like as this scales up to more than one session removed and replaced, this scheme could be more confusing than useful (e.g. someone wants to remove one of the sessions in the middle and shifts all their metadata to different sessions).

This part sounds like we're thinking about different things

Yes, if I remove a session from the sidebar or the session manager table (back completely backspacing out of that item in the list; again, should probably ask for confirmation somehow since that could occur accidentally), I acknowledge the loss of that information

All I'm talking about though is giving the session ID a different value as an in-place modification

> I could handle this case only when one session is replaced by a single session of a different name, where the new session now has the data from the previous session. Or some other constrained condition. Would that be an effective solution here?

Not sure about the implementation level details; that is, if you need to copy the session info in order to alter that one field

If I were doing this with Python data classes or similar, I would simply change that one value (session ID) in the structure instead of copying a new structure with that one changed value

**Comment by garrettmflynn** [comment]
So I think this might be a good place for test-driven development, as it'd be easiest for me to implement something that has clearly defined effects in the resulting data structure.

So here's how things currently work: 
```js
    const results = { 
       subject: { 
          original: {
               source_data: { }, // Actual source data structure
               metadata: {
                   NWBFile: { session_id: 'original' },
                   Subject: { subject_id: 'subject' },
               },
          } 
      } 
}
    const subjects = { subject: { sessions: ['renamed'] } }
    convertSubjectsToResults(results, subjects)
```

The `convertSubjectsToResults` function will mutate the results object to (1) delete the`original` property, then (2) a new object of the same structure is produced underneath the 'renamed' header. If other entries were placed in the sessions array, then additional properties underneath `subject` would be created. 

On the other hand, if `['renamed', 'original']` were used, this would not modify the original object and simply produce (2).

Based on the above discussion, what is the condition we want to cover and what is the desired output?

**Comment by garrettmflynn** [comment]
In order to ensure that the value in the `metadata.Subject.subject_id` property is only represented once as the Subject ID, I'd have to convert the object that holds sessions into an array, e.g.
```js
const results = { 
       subject: [
             {
               source_data: { }, // Actual source data structure
               metadata: {
                   NWBFile: { session_id: 'original' },
                   Subject: { subject_id: 'subject' },
               }
      ]
}
```

This would be fairly simple. Though defining rules that force the UI to reload when the `metadata.Subject.subject_id` property is updated would take a bit more time.

**Comment by garrettmflynn** [comment]
Having the subject and sessions IDs duplicated at the top level of this data structure is just an easy way to quickly look up particular session, subject pairs.

**Comment by CodyCBakerPhD** [comment]
OK thanks for the context!

I agree, test specification might be best here but for that I'd need to gain a greater understanding of the page data structures; let's discuss this in more detail in the meeting tomorrow (5/24)

**Comment by garrettmflynn** [comment]
As a summary of today's meeting, here are a set of issues that we'll need to solve to support the reliable association of array items (e.g. the strings in the "sessions" property) with other data (e.g. source_data and metadata for a particular session):
1. We should be ignoring subject and session ID in the file metadata so it is only mutable on the Subjects page
2. We will need to design a better editor for the sessions so things are clearly rendered as a visual list (where one modification happens at a time) rather than as a comma-separated list.
3. We should indicate that the sessions key is comma-separated using its property description.
4. We should provide a warning when swapping pages using the sidebar (e.g. ‘you have unsaved data. Would you like to save?’)
