### ISSUE TITLE
Zoom In / Out on Electron

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#214]
It would be great to have a zoom in/out option in the Electron app so that users can avoid tables that clip.

I've started a branch (https://github.com/NeurodataWithoutBorders/nwb-guide/tree/zoom-shortcut) that explores this idea. However, it seems like the required `CommandAndControl + numsub` command, as well as any others that have shortcuts like `numadd` and `numsub`, will not work on my Mac—otherwise this would be a fairly straightforward feature to implement

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
