### ISSUE TITLE
Create Dandisets using the REST API

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#221]
Instead of going to [dandiarchive.org](http://dandiarchive.org/), it would be ideal to create dandisets from the GUIDE itself by supplying a name and description on the `upload` page.

**Comment by bendichter** [comment]
I think we should allow users to append to an existing dandiset or to create a new one

**Comment by garrettmflynn** [comment]
I started working on this capability in the main WebNWB branch. You can find the current demo [here](https://github.com/brainsatplay/webnwb/tree/main/packages/dandi/demo).

While I can create a new dandiset using both cURL and the browser's `fetch` API, the browser receives an error code and doesn't return the appropriate metadata that will allow us to locate the dandiset after creation. 

This seems to be a CORS issue on the DANDI API itself, something that the browser would experience but other environments may not.

Here is the correct cURL call (token omitted): 
```
curl -X 'POST' \
  'https://api-staging.dandiarchive.org/api/dandisets/?embargo=false' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: token xxxxxx' \
\
  -d '{
  "metadata": {},
  "name": "string"
}'
```

**Comment by bendichter** [comment]
@garrettmflynn could you file an issue on https://github.com/dandi/dandi-archive?
