### ISSUE TITLE
Ensure that the user previews a session before moving onto the full conversion

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#223]
If we'd like to ensure that a user reviews a stub preview before moving onto the full conversion, we should block their progress from the File Metadata page until they press the Preview button for a session they've finished editing.

Since this review process is a best practice and, really, one that is easy to ignore if automated anyways, we don't necessarily have to block their progress—and instead might just be more clear about this expectation to preview before moving on.

**Comment by CodyCBakerPhD** [comment]
Two things still to improve here:

a) upon further reflection, the preview rendered in the event there are multiple sessions, should probably not be random. Find with just using the first session deterministically

b) We should however run stubs for ALL sessions prior to running the full conversion

This was something I found when testing one of the recent interface additions - I tested several datasets using several sessions - but many were different and some even had errors - but those were not detectable unless I specifically tried to preview each individual file the 'optional' way from the file metadata screen
