### ISSUE TITLE
Manage sessions through the Source Data instance manager rather than the Subjects table

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#224]
To allow the Subjects page to focus on subject data, we will move this capability to the Source Data instance manager. 

While doing this, we should make sure that there is the ability to add and remove sessions from each subject.

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD This is inconsistent with #482. Assuming we aren't pursuing this direction anymore?

**Comment by CodyCBakerPhD** [comment]
I think they're kind of compatible - the main idea was still to have the session management separated from the subject table

Whether or not that is a table on the same page or a button in the manager form on the next page is the main difference; the table seems simpler

**Comment by garrettmflynn** [comment]
Yeah I agree. Even if we moved the table to a separate page, the general idea of isolating Session specification from other metadata specification is a smart move for one-directional data flow. 

This Issue just seems overly attached to the method rather than that rationale, unlike #482

**Comment by CodyCBakerPhD** [comment]
replaced by #482
