### ISSUE TITLE
Easier access to conversion preview output stubs

### ISSUE THREAD

**Issue by jabekengineer** [NeurodataWithoutBorders/nwb-guide#259]
I would like easier access to the conversion stubs created by the conversion preview. It would be great if the stub path shown to the user could be a link to the parent directory. 

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/90007551/89c57b0e-6dde-4fe2-b182-f31a1a8e673e)

If i could click the link and view my file or even have it open in HDFView, that would be convenient for me.

Alternatively, it would be even better if I could specify the output folder of the conversion stub. 
This would make it easier for my lab to adopt GUIDE immediately as a metadata form which triggers my custom NWB conversion pipeline.

**Comment by garrettmflynn** [comment]
Clicking a button / the link to view the file in your file explorer is quite simple. 

@CodyCBakerPhD If users specify custom output folders (i.e. as already implemented for final conversion outputs), should we continue to impose a DANDI-like folder structure or not?

@jabekengineer Would a nested folder structure be agreeable for you, or would you prefer that the files output directly to the custom output location?

**Comment by CodyCBakerPhD** [comment]
> If users specify custom output folders (i.e. as already implemented for final conversion outputs), should we continue to impose a DANDI-like folder structure or not?

I would say yes; since `dandi upload` is the ideal 'final step' of a pipeline, if the output can already be pre-`dandi organized` in a sense it can reduce confusion in how things appear on the archive

There is now an easy-to-click button that leads you directly to your stub files from whatever directory you specified early on
