### ISSUE TITLE
[Bug] Fresh install: Pydantic

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#265]
Just did a complete wipe and reinstall of the GUIDE in dev mode on `main`

Backend wasn't able to run due to a vague pydantic error stemming from some DANDI import

Upgrading via `pip install pydantic==1.10.12` fixed the problem

**Comment by CodyCBakerPhD** [comment]
Rather odd that the CI doesn't catch this problem though... if no one else sees it on fresh install then I can brush it off as a fluke and close this

**Comment by garrettmflynn** [comment]
I haven't seen it but not on an M1. Maybe @rly better confirm?
