### ISSUE TITLE
[Bug] Fresh install: conversion subfolder

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#266]
Just did a complete wipe and reinstall of the GUIDE in dev mode on `main`

We recently changed some stuff about folder name paths so I wonder if that's what did it...

But I was able to reach the end of a pipeline, but when I tried to run the full conversion the backend complained that the path didn't exist

Manually creating the `conversions` subfolder in the nwb-guide home directory fixed the problem

**Comment by garrettmflynn** [comment]
Hmmm I'm running `resolved_output_path.parent.mkdir(exist_ok=True, parents=True)` before actually doing anything in the subfolder, where `resolved_output_path` includes the `CONVERSION_SAVE_FOLDER_PATH` (conversions subfolder).

Do you remember if it complained inside `neuroconv` or from the Flask server itself?

**Comment by CodyCBakerPhD** [comment]
Yeah, I could have sworn we tested that out at the time

The traceback led to the manager function that much I know

I just tried reproducing it the forcible way but this time it created the parent folder. Closing this for now then
