### ISSUE TITLE
[Bug] pyflaskdist crashes

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#267]
Ryan and I have mostly been able to get the build deployment pipelines working insofar as the frontend (and theoretically backend) is concerned

The biggest problem right now blocking functionality is that on all platforms, it seems the 'pyflaskdist' (separate from the dev mode server) that gets made from PyInstaller crashes on launch and so we're currently only able to run the frontend from the build version (which then fails at the interface screen of a pipeline since it can't load any from the backend)

**Comment by garrettmflynn** [comment]
Trying to fix this on Ryan's #256 branch. Still running into issues—but it's because of the PyInstaller build rather than the GUIDE's main JavaScript process now.

**Comment by CodyCBakerPhD** [comment]
Resolved in #302

**Comment by CodyCBakerPhD** [comment]
Though underlying problem still occurs, only on endpoint calls from the running flask server and not from the flask server itself, which launches fine now
