### ISSUE TITLE
[Testing] Add story pages for the source data screen for each interface

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#274]
@garrettmflynn To more easily catch events like the one detected in #247 I think it would be useful to have chromatic stories for the source data screen for each interface in order to track and detect unintended changes to global components

This might increase our snapshot usage, but TBH chromatic is proving invaluable for this kind of stuff so I'd say it's worth it if we have to pay for a few months during active development

**Comment by garrettmflynn** [comment]
To do this, we'll need an active instance of the NWB GUIDE backend running somewhere (e.g. the cloud) so we can get the proper schema. That or a simple way to request the schema using Pyodide or some other Python + browser solution.

Would you want to do this or would these considerations preclude such use of Chromatic?

**Comment by CodyCBakerPhD** [comment]
What about vitetest? Is there an easy way to add something analogous for that?

**Comment by garrettmflynn** [comment]
We still need access to the outputs of Python functions. We _could_ spin up the server and make API calls to the local instance if we're using `vitest`. Though actually confirming that we get what we expect requires exhaustive, hardcoded objects to match—and if we're setting a heuristic rule (e.g. only x,y, and z metadata property), it'll be pretty simple to modify the script to have the rule hold. 

We just haven't explicitly noted the rule to follow here across different interfaces. Previously, we just were showing required properties—but then sometimes we needed non-required properties to get an interface to pass. 

The inclusion of `load_sync_channel` is quite predictable given that the `onlyRequired` property has been unset and we are now working an explicit list of properties to ignore on this form. 

Can you think of other interface metadata properties that we'd want to hide off the top of your head?

**Comment by CodyCBakerPhD** [comment]
> Can you think of other interface metadata properties that we'd want to hide off the top of your head?

They will only be discovered as I try things out; I no longer recall off the top of my head how each was designed lol

What if we stored a bunch of pre-calculated and cached (in CI or perhaps Git if not that heavy) all the source schemas for each interface corresponding to the currently used version of NeuroConv? Could you harness those in any way for a story to 'accept' the schema as if the back end had calculated it on the fly?

**Comment by garrettmflynn** [comment]
That would work. Would be simple enough to generate them.

I’m essentially already doing that for the current demo data—but it’s
hardcoded rather than generated.

**Comment by CodyCBakerPhD** [comment]
OK then, let's tackle this in our meeting tomorrow. There are a couple ways of going about it depending on how the chromatic generation works
