### ISSUE TITLE
[Bug] Navigating to issue submission after restart popup

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#286]
This screen is nice

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/b15d0eac-7a2b-4bcb-90ab-2c8117cc2e5b)

when the app fails to work (connect to backend) after a certain timeout

And I like the link to the GitHub issues; however, if I click on it, it does not launch an external instance of my default web browser, instead it navigates to the website inside the app

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/dc4bc30f-13c4-4c6c-a5bd-c77c6cd6548a)

while this is a cool idea, it does force me to sign in to GitHub manually instead of using my already logged in web instance and password manager

I also cannot proceed backward or forward through the webpages, so if I navigate anywhere inside the window I get stuck, unlike a normal web browser

I'd suggest just launching the link externally like we do with other links (i.e., to the docs) to avoid this kind of issue

**Comment by garrettmflynn** [comment]
Good catch, easy fix. Will do this ASAP
