### ISSUE TITLE
[Cody's Windows JS Error Collection]

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#311]
I'll just start a little collection of screenshots of these since they do not occur within our standard loggers or dev consoles; the window itself isn't even copy/pastable

**Comment by CodyCBakerPhD** [comment]
Running `npm start` in dev mode from the neurosift branch

Everything worked fine - *there was no problem with the app* - I'm just leaving this here as a record in case we ever see it again

Upon closing down the application (top-right X button on Windows)

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/29938eb4-087d-4861-a8ed-f134b68e9386)

**Comment by CodyCBakerPhD** [comment]
Selecting 'OK' actually triggers follow-up window errors too, slightly different

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/2786cea8-df42-4821-a23c-04ad3b8b7a0d)

**Comment by CodyCBakerPhD** [comment]
For provenance, the first time I saw something like this was in https://github.com/NeurodataWithoutBorders/nwb-guide/pull/283#issuecomment-1675979061

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/524e9911-8942-4f2c-9779-d46a65c8f121)

**Comment by garrettmflynn** [comment]
These are errors thrown by the main Electron process. The Object ones occur when trying to send messages to the browser window that has been destroyed—an issue that I believe was fixed in a recent PR (which I'll link here momentarily) by keeping better track of the open state.

**Comment by garrettmflynn** [comment]
I'm assuming you got these errors after merging? I'll have to do a bit more digging if that's the case to see what messages are being thrown after window closure.

**Comment by CodyCBakerPhD** [comment]
Huh, new one today

This one showed up - not immediately - but rather when I first woke my computer up (I usually just put it to sleep over night)

I had closed the app earlier the night before

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/36f35377-653a-4afd-85ab-1f4e66a8055d)

**Comment by garrettmflynn** [comment]
Hmmm this looks like the Python server didn't close correctly, threw a message when you opened your computer, and an attempt was made to send this to a non-existent BrowserWindow object.

I'm not sure how to replicate this but it's easy enough to make sure messages aren't sent when the window doesn't exist—previously I was just sending regardless of this if it was detected as "ready", which also seems to be a bit off.

**Comment by CodyCBakerPhD** [comment]
New one

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/c75dbdf8-8d1f-4797-9a31-f7e96143c1ab)

**Comment by garrettmflynn** [comment]
@CodyCBakerPhD These are pretty case-specific and no longer triggered. Do you want to keep this open or close it to clean up the Issues page?

**Comment by CodyCBakerPhD** [comment]
Oh, you're right I haven't seen these in a while now - thanks for fixing whatever it was 😅
