### ISSUE TITLE
[Text Bug] Stub preview progress bar

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#331]
The text for running stubs still refers to testing on a random session, but it now tests all sessions and even lets us preview all of them 

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/11243bce-0390-4ae8-bc9b-46348350a227)

**Comment by garrettmflynn** [comment]
Just checked and `main` uses a different, correct message. Do you know what branch you were using?

![stub_message](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/46533749/4070571f-29a0-4be4-b1ce-36818798ec2b)

**Comment by CodyCBakerPhD** [comment]
> Do you know what branch you were using?

#326 and #244 definitely, but both when they were up to date with `main` (#326 tested just now)

**Comment by CodyCBakerPhD** [comment]
I did just confirm that `main` looks fine - maybe it was a bad merge conflict with #326?

**Comment by garrettmflynn** [comment]
You got it. Just fixed on #326.
