### ISSUE TITLE
Preload imports on startup from safe endpoint

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#340]
@garrettmflynn Can you point me to the relevant code on the front-end that launches the first call to the Flask endpoint? (I think it used to have something about 'echo'? Or maybe it's the thing that checks if the backend is connected and running?)

I'd like to add a simple endpoint to trigger various imports just after launch (but as separate hidden operation) to reduce the instantaneous speed of the now locally scoped operations

**Comment by garrettmflynn** [comment]
https://github.com/NeurodataWithoutBorders/nwb-guide/blob/54681eb66f6e6c11f9bf5776b6176195a9681d13/src/renderer/src/index.ts#L99
