### ISSUE TITLE
[Bug?] Deletion of pipeline does not clear folder contents in `stub`

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#344]
I didn't check the other content folders, but the following workflow can reproduce this

-> open the stub folder for the GUIDE
-> delete existing tutorial pipeline
-> folder and its contents are still present
-> so if I regenerate a new tutorial pipeline, it still has all the previous contents

These should be cleaning up on deletion, right?

**Comment by garrettmflynn** [comment]
Oh sure. Good catch
