### ISSUE TITLE
[Bug]: Error popup window is clipping to the right

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#345]
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/1b0ef5b1-3ca9-4f3c-93d7-467ee0cde2bb)

I can't move/adjust the screen to include the full popup of the error on the bottom right

**Comment by CodyCBakerPhD** [comment]
Never mind the actual source of the error, as it's unrelated and is a Windows dev mode thing as far as I can tell

**Comment by garrettmflynn** [comment]
These popups have a maximum width and don't wrap well with long strings. Because of this, I updated this in #348 since the same issue was found. Now the max width is much larger and long text will wrap—though this isn't always pretty.
