### ISSUE TITLE
multiple probes/shanks neural data 

### ISSUE THREAD

**Issue by parviz-gh** [NeurodataWithoutBorders/nwb-guide#356]
hello , I am recording from multiple npx shanks simultaneously in each session . I dont know how to select all lfp and Ap data and add them to aquisition module using nwb-guide ?

**Comment by CodyCBakerPhD** [comment]
Until we add the SpikeGLXConverter option, the workflow you'll have to use is:

Select one AP and one LF Interface from the interface selection page per imec probe

For the source data page on each interface, choose a different AP/LF band from a different probe for each interface

We plan to extend the tutorial to generate multi-probe multi-gate example SpikeGLX format to better showcase this feature

**Comment by CodyCBakerPhD** [comment]
@parviz-gh By the way, we're currently looking for alpha testers to do one-on-one walkthroughs with

If you'd be interested, you can sign up for it here with [this link](https://docs.google.com/forms/d/e/1FAIpQLSfGDRug9W8XQfDuIF3OXLe3GYJ-dLM-B22Yv2_-yOuoMzIoOQ/viewform?usp=sf_link)

**Comment by CodyCBakerPhD** [comment]
Hi @parviz-gh, I'm clearing out some old issues

The current release of the GUIDE (v0.0.15) and current `main` branch support ecephys metadata from multiple recording interface which could correspond to different probes (to be indicated as different devices through the app)

Is it OK if I close this now?
