### ISSUE TITLE
[Bug] DANDI Upload via final guided mode page

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#357]
Might be Mac specific - haven't tried other platforms yet

Ran through a fresh tutorial in dev mode, worked fine until I reached the final DANDI upload page

I specified my staging dandiset ID but this error was thrown to dev console

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dandiset_id')
    at GuidedUploadPage.beforeSave (GuidedUpload.js:20:50)
    at GuidedUploadPage.save (Page.js:96:39)
    at GuidedFooter.onNext [as __onNext] (GuidedUpload.js:28:24)
    at EventPart.handleEvent (lit-html.ts:2003:29)
beforeSave @ GuidedUpload.js:20
save @ Page.js:96
onNext @ GuidedUpload.js:28
handleEvent @ lit-html.ts:2003
await in handleEvent (async)
handleEvent @ lit-html.ts:2003
```

**Comment by CodyCBakerPhD** [comment]
The error additionally occurs if I attempt to navigate away from the page with the 'Exit' button, meaning I must hard close/restart the app to get back to the main page

**Comment by CodyCBakerPhD** [comment]
Note that since this was a fresh install and generation of tutorial pipeline, I did not have my DANDI API key set on the settings page, just in case it was that rerouting that was potentially causing problems here

**Comment by garrettmflynn** [comment]
Fixed this. Just was accidentally accessing keys in an undefined object (that would then get defined) within an essential callback.
