### ISSUE TITLE
[Bug] Displays 'loading valid interfaces...' even after loading is complete

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#362]
When I do _not_ generate a tutorial pipeline (this is a fresh custom one starting with empty interfaces)

The following appears even though all the interfaces are already loaded when I press the button

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/3bb21dfe-e123-4174-880e-1ffdb3db351a)

**Comment by CodyCBakerPhD** [comment]
Not a huge deal, not a high priority - just leaving here as a note

**Comment by garrettmflynn** [comment]
Fixed with https://github.com/NeurodataWithoutBorders/nwb-guide/commit/f7ce052d7f1517ce4eb9c75c04cf84bc50002de5
