### ISSUE TITLE
Upload to staging server

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#367]
- [ ] Settings page should include a DANDI staging API key, which is different from production API key
- [ ] Upload page should include a checkbox for staging
<img width="802" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/02a2e703-b0f7-4db4-973c-c9e6c573c6ff">

**Comment by bendichter** [comment]
Also, there should be a warning on the upload page if no API key is present.

Also, API should be in all caps. API, not Api.

**Comment by CodyCBakerPhD** [comment]
> Upload page should include a checkbox for staging

This is not needed as it is determined based on the unique signature of the DANDI set ID

Storing both keys is a good idea though, as long as each entry box has a clear description of the difference

**Comment by bendichter** [comment]
> This is not needed as it is determined based on the unique signature of the DANDI set ID

OK, it wasn't clear to me from the user interface that this was determined automatically.

When we have the GUIDE create a dandiset, we will need to have control over whether a dandiset is being created in prod or staging, so even if it's not needed yet it will be needed soon

**Comment by garrettmflynn** [comment]
That's fair. It's easy enough yo add it when we need to, 'staging' is still an input to the Python functions (albeit autopopulated on the frontend) and will be possible to specify for creation as well.

I'll add a note that it is derived from the dandiset_id for the time being.
