### ISSUE TITLE
[Discussion] Encryption of DANDI API keys?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#369]
We are currently hiding the main page display of the API keys using the black dots convention, which is good because then someone can show or record their use of the guide without revealing their API key publicly

But I just noticed that we're dumping the DANDI API keys to the config.json file in the home directory for the GUIDE

As such, anyone could go into that file and they would display; or anyone could obtain these if they accidentally shared the config file

Should we be instead locking these keys away using encryption/password protection?

**Comment by garrettmflynn** [comment]
We could always encrypt the key when saved in the configuration file. However, we'd need a way to determine the salt for the consistent encryption algorithm that is not stored in a file (or at least the same file). 

Maybe we use the absolute file path to the NWB_GUIDE folder?

**Comment by CodyCBakerPhD** [comment]
> Maybe we use the absolute file path to the NWB_GUIDE folder?

Depends, do we support the act of users moving their home GUIDE folder?

**Comment by CodyCBakerPhD** [comment]
The general idea of pinning the info to the platform on which the app is installed is sound, however.

**Comment by garrettmflynn** [comment]
IMO we wouldn't support moving that folder. We only know where it is to begin with because it's hardcoded
