### ISSUE TITLE
Values in NWBFile and Subject pages are not saved

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#387]
**Describe the issue**
When going through the tutorial or creating a new project, values entered in the NWBFile and Subject pages are not saved and not used to populate later pages.

**To Reproduce**
Steps that leads to the issue:

1. Open NWB GUIDE
2. Click Tutorial
3. Select Test Data Directory Path
4. Click Generate Dataset
5. Click Open Conversion Pipeline
6. On Guided Mode page, click Next
7. On Project details page, click Save and Continue
8. On NWBFile page, enter "Test" into Experiment Description box
9. Enter "Ly, Ryan" as an Experimenter
10. Enter "Test" into Institution box
11. Click Save and Continue
12. On Subject page, enter "Test" into Description box
13. Enter "Test" into genotype box
14. Enter "M" into Sex
15. Enter "Mus musculus" into species box
16. Click "Save and Continue" or "Populate Subject Details"

Entered Sex, Species, Genotype, and Description values are not in the Subject Metadata table.

17. Enter some values for those.
18. On Inspector page, I see that Experimenter, Experiment Description, and Institution are flagged as missing.

This issue is also observed simply by entering values into the NWBFile page, clicking Save and Continue, then clicking Back and seeing the entered values are missing.

**Operating system used:**

- OS: Mac M1, latest commit on main

**Comment by garrettmflynn** [comment]
Can you try #376 to see if that fixes it?

**Comment by rly** [comment]
> Can you try #376 to see if that fixes it?

It does! Great.
