### ISSUE TITLE
[Feature]: Expose number of jobs/threads for DANDI upload

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#426]
Will require exposing these to NeuroConv as well

A number of people (about 50%) ran into segmentation faults during upload that traced back to joblib in the dandi organize (which would also have then affected parallel upload as well)

**Comment by garrettmflynn** [comment]
Do you want this exposed as a user-defined value, for the REST API request, or simply just as a hardcoded value for the `automatic_dandi_upload` call?

**Comment by CodyCBakerPhD** [comment]
> Do you want this exposed as a user-defined value, for the REST API request, or simply just as a hardcoded value for the automatic_dandi_upload call?

A user selection is desired - I'll put together the schema for it when I expose it, as long as there's an integer range selector component I assume it should work fine? (or I can also generate an enum of strings on the fly if that's easier?)

**Comment by garrettmflynn** [comment]
Either works. If you'd like to restrict users to a certain set of non-consecutive values (e.g. powers of 2), I'd use enum—otherwise we could also specify a min and max value.

**Comment by CodyCBakerPhD** [comment]
fixed by #486
