### ISSUE TITLE
[BUG] `GLIBC_2.33` not found, from the release `NWB-GUIDE-0.0.10.AppImage`

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwb-guide#441]
**Describe the issue**
Missing library error when running GUIDE from the release `NWB-GUIDE-0.0.10.AppImage`

```
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_NWB-GUzHqHG0/resources/flask/libstdc++.so.6)
```

**To Reproduce**
Following either the Graphical Interface or the CLI instructions in the README yields this error. With the Graphical installation, the errors popup in the GUIDE GUI, using the CLI you can see the error track in the terminal.

**Expected behavior**
Libs should be present in the distribution.

**Screenshots**
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/24541631/f4804689-6954-4f1d-b0ef-138cf8d93859)
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/24541631/bd5b57ed-32e2-42ea-8d54-cb42a4ef51a2)

**Operating system used:**

- OS: Ubuntu 20.04.5 LTS

**Additional context**
GUIDE runs fine without these errors if I run it locally directly from source code in `main`.

**Comment by CodyCBakerPhD** [comment]
> GUIDE runs fine without these errors if I run it locally directly from source code in main.

Alas, you are not alone in this. We are planning to retire the `.AppImage` linux distributable entirely and direct users on that platform to simply install using the dev instructions
