### ISSUE TITLE
[BUG] Can't Generate Dataset on tutorial - Ubuntu

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwb-guide#442]
**Describe the issue**
Error when generating dataset for the tutorial. I'm running from source code at `main` branch.

Error track:
```
[2023-10-12 11:18:55,114] ERROR in app: Exception on /neuroconv/generate_dataset [POST]
Traceback (most recent call last):
  File "/mnt/shared_storage/Github/nwb-guide/pyflask/apis/neuroconv.py", line 232, in post
    return generate_dataset(**neuroconv_api.payload)
  File "/mnt/shared_storage/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 508, in generate_dataset
    copytree(spikeglx_base_directory, spikeglx_output_dir)
  File "/home/luiz/anaconda3/envs/nwb-guide/lib/python3.9/shutil.py", line 566, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/home/luiz/Desktop/testguide/spikeglx/Noise4Sam_g0'
```

**To Reproduce**
Steps that leads to the issue:

1. Go to Tutorial
2. Click on Test Data Directory Path
3. Click on Generate Dataset

**Expected behavior**
Data to be created without errors.

**Screenshots**
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/24541631/f52ae017-ce23-431a-b2c6-2a96fb59deab)

**Operating system used:**

- OS: Ubuntu 20.04.5 LTS

**Comment by CodyCBakerPhD** [comment]
The current instructions for generating the tutorial dataset are illustrated below the file selector; it needs to point to the `ephy_testing_data` folder itself

We are however refactoring this to work as you intended to use it, where no pre-existing data in any structure is required to generate the example

**Comment by garrettmflynn** [comment]
Instruction for the legacy tutorial have been provided above.

This has now been replaced by an autogenerated tutorial dataset (#530).
