### ISSUE TITLE
Clarify When User Needs Main vs. Staging API Keys

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#454]
During our user tests, it was made apparent that it's unclear that you don’t need the Main API key at the same time as the staging API for the tutorial. While this was fixed in #438 with further documentation on the Tutorial page, there still remains some ambiguity as to when you need each API key.

How can we make clearer which API key you need when?

When the user is redirected to the Settings page because the required API key doesn't exist, we indicate _directly_ in the popup which of the API key fields is missing. Maybe we auto-focus that input?

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn I feel like this has been elaborated across various descriptions now - agree?

**Comment by garrettmflynn** [comment]
Yep! This has been achieved at several different levels.
