### ISSUE TITLE
Make staging key in settings not strictly required

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#469]
I'd suggest separating the DANDI keys into different tabs on the settings, and also having only the main key be required (i.e., show up as red status when missing)

The staging, for the majority of actual use cases beyond the alpha testing and optional tutorial completion, will mainly be for developers (also requires different permissions on DANDI side, apparently) - so I'd either not show a status requirement or if you need to, show it as yellow instead of red

**Comment by garrettmflynn** [comment]
Thanks for the suggestion! I'd made the staging API key optional on the schema—but I didn't stop validating it for the correct form, which failed when it was empty.

Just pushing a PR to fix that.
