### ISSUE TITLE
Allow Forcing Global Values After Manual Interaction

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#504]
Currently, it is not possible to re-assert the applicability of Global Metadata after someone has manually interacted with an input—particularly a checkbox (boolean) input. We currently assume that checkboxes are always decoupled after interaction, whereas other inputs revert to the Global Metadata if cleared (i.e. cannot be empty if a global is set).

We need a way to allow for global values to assert themselves despite previous manual interaction.
 
### Checkboxes
To do this, we could have a "Force All" button on the global metadata popup, which will present a warning that this will overwrite any existing manual values.

## Other Inputs
Similarly, we could include a "Force Empty" button that could take the place of automatic reversion to the Global Value.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn How does the current global metadata behave? Is this needed any longer?

**Comment by garrettmflynn** [comment]
If a global default is specified, most inputs will fallback to this if cleared (e.g. text inputs, arrays, etc.). 

However, checkboxes _don't have a way to be cleared_, so they're stuck with the user-defined state after the first interaction.

This would still be a nice feature to have—but we haven't had too many issues with it. There are very few checkboxes in the GUIDE at the moment

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
