### ISSUE TITLE
Allow Explicit Inclusion and Exclusion in Locate Data

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#510]
Currently, we have a boolean for including existing data on the Locate Data page, which allows for you to run multiple searches using different format strings while maintaining old subjects, whether automatically or manually-defined.

@rly proposed a more explicit strategy, where:
1. Users explicitly choose to add / remove more format strings per interface
2. Manual additions are shown as a separate list that can be deleted.

**Comment by CodyCBakerPhD** [comment]
I think this interface has improved considerable over time and these specific aspects are no longer needed
