### ISSUE TITLE
Convert Modality Metadata (e.g. Ecephys, Ophys, etc.) Tables into Pop-Up Forms

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#512]
@rly suggested that we (optionally) convert Modality tables into lists like the Experimenter (NWBFile) field that open a modal-based form when you add, for instance, an ImagingPlane (Ophys). 

When created, these tables are represented as their keyColumn (usually Name), possibly including an expandable set of additional information in small dropdowns.

This solution would use loose selectors (like [HandsOnTable Autocomplete cell type](https://handsontable.com/docs/5.0.1/demo-autocomplete.html)) that suggest values based on those of other rows of the same "table".

**Comment by CodyCBakerPhD** [comment]
Need more details/info about what this feature would entail @rly 

Can you describe it in more detail?

Was this the same idea as having 'profiles' for experimenters that can make it easier to add or link institution, lab, etc.?

**Comment by CodyCBakerPhD** [comment]
Some subfields do pop up now, but the currently table split looks pretty good for the time being
