### ISSUE TITLE
[Idea] Table auto-population via dragging or control

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#517]
Insert value into top cell then drag down (or something similar) to autocomplete

**Comment by garrettmflynn** [comment]
This was suggested by [@forrest](https://github.com/Argzero) during one of our SfN demos 🙂

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
