### ISSUE TITLE
Trying to install on Linux. I don't see .AppImage file in gh release

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/nwb-guide#518]
I would like to install this on my Linux machine. I read the docs and it told me to download an .AppImage file. But I'm not sure where to find that file. I looked here: https://github.com/NeurodataWithoutBorders/nwb-guide/releases

**Comment by garrettmflynn** [comment]
Which docs are you referring to? The latest should ask you to use the linux-fix branch of the GitHub repo: https://nwb-guide.readthedocs.io/en/latest/installation.html

**Comment by magland** [comment]
I went here first:
https://nwb-guide.readthedocs.io/en/latest/installation.html

And then I clicked the link to go to the linux-fix
https://github.com/neurodatawithoutborders/nwb-guide/tree/linux-fix/

Then I clicked on documentation again thinking it would be different, but I guess that brought me back to the main docs.

So I guess it says "developer installation instructions" but I'm not sure where to find those. It would be helpful if there was a link that brought me there, otherwise I need to poke around the branch to try to find it.

**Comment by garrettmflynn** [comment]
Ah thank you for spelling it out for me! We just merged `main` into the branch, which removed the explicit installation instructions that were there. 

Sounds like we should rewrite the following:

> Please follow the Developer Installation instructions on the [linux-fix](https://github.com/neurodatawithoutborders/nwb-guide/tree/linux-fix/) branch of the NWB GUIDE.

To something like:

> Please clone the [linux-fix](https://github.com/neurodatawithoutborders/nwb-guide/tree/linux-fix/) branch of the NWB GUIDE and follow the [Developer Installation instructions](https://nwb-guide.readthedocs.io/en/latest/developer_guide.html#installation) on this documentation.


@CodyCBakerPhD Do you agree?

**Comment by CodyCBakerPhD** [comment]
> Please clone the [linux-fix](https://github.com/neurodatawithoutborders/nwb-guide/tree/linux-fix/) branch of the NWB GUIDE and follow the [Developer Installation instructions](https://nwb-guide.readthedocs.io/en/latest/developer_guide.html#installation) on this documentation.

Looks fine to me
