### ISSUE TITLE
Missing progress bars?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#523]
I started to notice this towards the end of SfN but unsure when exactly it started happening

This page used to show 1/4 (number of files converted) and a progress bar that would increase every time a file was written

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/84448fdb-9866-4f08-badd-dafc6937c151)

**Comment by garrettmflynn** [comment]
Must have snuck in when allowing users to cancel requests. Fixed here: https://github.com/NeurodataWithoutBorders/nwb-guide/commit/c52b6e9f539e247f1f8890de2f9c240facf3bbd4
