### ISSUE TITLE
[Feature] Intuitive interface for inferring path expansion

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#528]
I have an idea for how to make the path expansion interface more intuitive:

1. They select a file or folder for the data from a single data format for a single session.
2. The user is prompted for the subject_id and session_id of that selected session.
3. Using 1 and 2, we generate the path template where we have already replaced those values with {session_id} and {subject_id}. We tell the user how many files we have found that match this pattern and provide a button so the user can see the list of paths found.
4. We link to the existing additional instructions how to refine this template with format strings or extract additional metadata, which can safely be skipped in most cases.

**Comment by garrettmflynn** [comment]
Awesome! This sounds great.

**Comment by CodyCBakerPhD** [comment]
Yes, this could help immensely - it can also start off as a helper function on NeuroConv so that it isn't just a GUIDE specific feature

```python
def construct_format_string_from_path(path: str, session_id: str, subject_id: str) -> str:
    inferred_format_string = ...
    return inferred_format_string
```

Possible for either `_id` to be blank `""`, but at least one must be non-blank; another case to consider is when they are both equal to the same value (not uncommon for some subjects to only have one session of data such that the session ID is just the subject ID)

@bendichter did you want to start a PR for this or did you want me to take a crack at it?

**Comment by bendichter** [comment]
@CodyCBakerPhD I think `construct_format_string_from_path()` would simply be:

```python
def construct_format_string_from_path(path, session_id, subject_id):
    return path.replace(session_id, "{session_id}").replace(subject_id, "{subject_id}")
```

Is that worth adding to NeuroConv? Alternatively it could be done purely in the front-end.

**Comment by CodyCBakerPhD** [comment]
Some design ideas for the frontend of this


- GUIDE design for path specifier helper
  - To the right of the ‘format string path’ entry form, pop up a modal window
  - File or folder selector: starts at base path; user selects example
  - Enter subject ID for this file
  - Error if subject ID is not found
  - Enter session ID for this file
  - Error if session ID is not found
  - Ability to enter extra key-value pairs
  - OK button: When pressed, the modal window disappears and the constructed string is auto-populated. This string can be edited further by the user to add more metadata but they should be able to continue without editing
