### ISSUE TITLE
Suggestions to improve home page user experience

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#531]
Some of these ideas were discussed at SfN.

The three panels with the lotties on the home page draw your attention and look like they should be buttons. Both @oruebel and I have tried to click them before.

I think the main use cases of people using NWB GUIDE are:
1) Convert a new dataset to NWB
2) Resume a conversion pipeline

and less so:

3) Inspect an NWB file
4) Visualize an NWB file
5) Upload an NWB file to DANDI

outside of the conversion process

As such, I think the Conversions page, which has buttons for Convert and Resume, should be the home page, and the current home page should be removed and the option for Home in the left sidebar should be removed.

To make the Conversions page more home-page-like, I would adjust the text at the top:

The current text on that page "The NWB GUIDE walks users ..." is a wordy description of the app and IMO not useful for users. We could move that to the top of the Documentation page.

The text at the top of the current home page could be moved to the top of this new home page. It currently says "... converting and uploading NWB datasets ..." which to a novice user _might_ suggest that you are converting NWB datasets = converting data already in NWB to another format. I think the phrasing "Your one-stop tool for converting data to NWB and uploading it to the DANDI Archive!" would be clearer. 

I think the subtitle "Start new conversions and resume existing ones." is unnecessary. The title "Your conversions" may also not be necessary, especially if we have the text "Your one-stop tool..." at the top. 

Alternatively, we could keep the current home page and have five buttons on it, one for each of the actions listed on the left sidebar. But I think (1) and (2) will be the most used, followed by perhaps (4), so taking users directly to (1) and (2) would save users a click and knowledge of another page.

Let me know what you think. I'd be happy to mock this up for feedback and implement it.

**Comment by garrettmflynn** [comment]
I like this! IMO the home page is really only an aesthetic feature—otherwise there isn't much there and it's nearly always ignored or confusing to interact with.

You're welcome to tackle those adaptations. I was going to finish submitting PRs for our milestone features (DANDI, metadata, etc.) before handling any UI-focused updates from user testing, so it'd be great to have the help on it :)

**Comment by rly** [comment]
I like the home-redesign prototype much more than v2. Thanks for putting that together! One minor suggestion -- if there are no existing conversion pipelines, can you make this bit now show up?
<img width="816" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/0d037aad-be57-49ab-9d81-98523b14c32c">

It would make less visual clutter, and this is currently how this page works on the "main" branch.

**Comment by garrettmflynn** [comment]
What is it you'd like me to change? If I clear my pipelines, I seem to have the same behavior across branches:

## Main
<img width="915" alt="Screenshot 2024-01-01 at 1 57 51 PM" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/46533749/3747062e-c630-4744-88ef-5759bb569025">

## Home Redesign
<img width="918" alt="Screenshot 2024-01-01 at 1 58 10 PM" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/46533749/a61ee367-21be-4de6-92e2-f4d043011972">

**Comment by rly** [comment]
Huh, I tried again and that "Existing Conversions" header isn't there anymore! I suggest moving forward on the home-redesign branch. I made slight modifications to the text and button (dashed->solid border). It could be prettier but IMO it's a more functional design than the current main branch homepage. 

<img width="798" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/f8aed539-a1fb-4f53-ba0a-4cfb2e563f89">

**Comment by rly** [comment]
On second thought, the "Welcome to NWB Guide!" is not totally appropriate if this is not your first time going to that page. Perhaps we should have a separate first-time pop-up screen that introduces users to NWB GUIDE and suggests that they do the tutorial.

**Comment by garrettmflynn** [comment]
Completed with #555
