### ISSUE TITLE
Expose TimeIntervals Interfaces (trials, epochs)

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#538]
NeuroConv supports conversion of CSV and Excel data to TimeIntervals neurodata types:
https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/text/csv.html
https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/text/excel.html

This includes trials, epochs, and custom TimeIntervals tables. These are very common in neurophysiology experiments. We should allow a user to select a CSV/Excel interface and then specify a path to the CSV/Excel file with the correct column headers. This assumes that timestamps are already aligned or will be aligned in a separate downstream step.

In a future iteration, we could also have a page where users can copy and paste a time intervals table into the app and edit it in the app.

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/847

Re-open again whenever this starts active development
