### ISSUE TITLE
[Bugs]: Restoring progress from past conversions

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#55]
Copied from https://github.com/NeurodataWithoutBorders/nwb-guide/pull/52#issue-1634528176

## Bugs to Resolve in Future PRs
1. Reloading a project will not maintain the navigation sidebar behaviors from the earlier session
2. Completed conversions are not transferred to the Completed tab on the start page

**Comment by CodyCBakerPhD** [comment]
We should also discuss if we even want a 'completed' classification for a pipeline

Sometimes you want to rerun it to adjust something you didn't think about initially, or run additional sessions at a future time when the only thing you change is the folder paths (this factors into the next 'experiment' level design a bit of course)

**Comment by garrettmflynn** [comment]
Makes sense. I’ve already designated these as “Successful Conversions” in a
follow-up PR since these issues also stood out to me.

**Comment by garrettmflynn** [comment]
(1) was resolved in #57 and (2) was resolved in #54
