### ISSUE TITLE
Specify Cross-Row Table Values on Global Metadata Popup

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#553]
It would be great to, for instance, specify `NaN` for `excitation_lambda` in all rows of the `Ophys.ImagingPlane` table using the Edit Global Metadata button on the File Metadata page. 

This will require using the schema returned from NeuroConv as the base for this global metadata instead of our hardcoded schema.

**Comment by CodyCBakerPhD** [comment]
I think this is through now?
