### ISSUE TITLE
File Metadata Pre-Input Form

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#554]
As discussed with @CodyCBakerPhD, it would streamline the user workflow to have a popup pre-form for the File Metadata page (which automatically opens on first visit) that allows users to answer a series of simple yes/no questions to filter the possible interactions available in the rest of the form.

As a concrete example, we discussed a sub-series of questions that included "Do you know the Emission Lambda values of your Optical Channels?", "Are all Emission Lambda values the same?", and finally "What is the value of Emission Lambda?".

Paired with #553, this would allow us to populate global values as a result of the user's answer to these questions and/or hide interactions with related inputs so there is less to focus on for the rest of the File Metadata page.

**Comment by CodyCBakerPhD** [comment]
Since this app was so inspired to be the TurboTax for NWB conversions, I'll be noting all kinds of things whilst filing this years taxes

TurboTax uses pre-input forms like this prolifically to simplify the main data entry portions

**Comment by rly** [comment]
I very much agree, especially for NWBFile metadata. Something like:

If the institution name is the same for all of your sessions, what is the institution name?
[Text box]
[Button "Next"] [Button "Let me enter for each session later"]

Same for experimenter name, keywords, related publications, etc.

Same for subject species and sex and maybe some of the other subject ones, but definitely those two.

**Comment by CodyCBakerPhD** [comment]
closed by #633 

We'll continue to refine over time
