### ISSUE TITLE
Export Inspector report as txt file

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#568]
For both debugging and interoperability in general, it would be nice to add a 'export to text file' button to the inspection (both pipeline and standalone tool) instead of entirely relying on the in-window rendering of the messages

**Comment by garrettmflynn** [comment]
Is a `.json` file alright or would you prefer a reproduction/request of the `format_messages` output?

**Comment by CodyCBakerPhD** [comment]
The CLI usage allows both via two pathways; so being able to choose either works here

If JSON is the requests format, https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/nwbinspector.py#L298

If structured text, then https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/nwbinspector.py#L304

**Comment by CodyCBakerPhD** [comment]
added in #569
