### ISSUE TITLE
ScanImage session start time display

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#570]
Generate a fresh ScanImage SinglePlane SingleChannel testing pipeline and navigate to the file metadata page

The session start time field will be correctly yellow (it is found within the ScanImage header) but the value is not displayed in the datetime selector, making it seem as if it is unknown

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/94ec055a-c3ff-4ab7-b4a2-2bce8d7a6280)

**Comment by garrettmflynn** [comment]
So the reason is that the value for this is `2022-08-08T16:44:29.124000`, though JavaScript date-time selectors only allow for `2022-08-08T16:44:29`. What is that last trailing bit?

**Comment by garrettmflynn** [comment]
We can either fix this so it isn't passed from NeuroConv, truncate the misformatted string so it's valid, or throw an error indicating it isn't valid. 

Is there one you'd prefer?

**Comment by CodyCBakerPhD** [comment]
> What is that last trailing bit?

Precision to the microsecond; these originate as Python datetime, and that's what it reads. It's often stored that way on the acquisition systems and their storage formats too, such as unix time

Ideally we wouldn't lose that precision here

**Comment by garrettmflynn** [comment]
Got it. I'll make sure the raw value is stored while the truncated value is displayed.

Is that sufficient as a solution? There's no way to select to the microsecond manually.

**Comment by CodyCBakerPhD** [comment]
Sure thing

**Comment by CodyCBakerPhD** [comment]
I could see a future user desiring more precision if it's something they have documented externally and is important for cross-file reasons, but that's an edge case that we can wait to hear a request on before adding it

> There's no way to select to the microsecond manually.

Not from that selector, but you can always add an extra field next to it if need be; I agree for now that would look awkward though
