### ISSUE TITLE
[Bug] Adding items to list on General Metadata not working

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#587]
**Describe the issue**
When I try to add an experimenter or related publication, I get an error:

<img width="1392" alt="Screenshot 2024-02-05 at 11 33 07 PM" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/3ccc24ae-b37b-48a4-8fb9-2f216f65fa0a">

When I try to add a keyword, I just get another popup with a button "Add Property"

**To Reproduce**
Create new conversion pipeline for SpikeGLXRecordingInterface and go to General Metadata accordion. The behavior is the same for a single session and for global metadata.

**Operating system used:**
Mac M1 on main branch

**Comment by CodyCBakerPhD** [comment]
Can confirm this on my side @garrettmflynn is it possible to add an end to end test for this when you fix it?

**Comment by garrettmflynn** [comment]
Yep caught this while testing too. Just finished the update, I'll add a test

**Comment by garrettmflynn** [comment]
Closed with #600
