### ISSUE TITLE
Update 'Documentation' page

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#59]
Would be one of the good first tasks by @rly 

Currently looks like

![image](https://user-images.githubusercontent.com/51133164/227282261-6a3465b0-4dd4-49ff-b849-9331303657c9.png)

Needs to be updated to point to all the right kinds of places in the NWB ecosystem, which I leave to @rly

**Comment by rly** [comment]
Add funding information. Powered by neuroconv. Point people to information about the team.

**Comment by CodyCBakerPhD** [comment]
@rly This and #60 are now top priorities - should be very quick and easy to fix
