### ISSUE TITLE
Move Back/Next buttons to the bottom right and Return Home button to bottom left

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#590]
I was watching a user go through NWB GUIDE today and noticed that his mouse kept instinctively moving to click the "Return to Home Screen" button in the bottom right instead of the "Next" button. I think it is more common to have the "Next" button in the bottom right. What do you think about moving it?

**Comment by CodyCBakerPhD** [comment]
Where would you propose moving the 'home' button to on the following screenshot?

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/c3dc2785-0b77-44e8-a52b-13c36f1a2669)

In general I agree, the 'next' button is usually towards the right of the screen. But it's also highlighted to draw visual attention and could just be one of those 'learning curve' things that people get used to over time

**Comment by rly** [comment]
I would say move both "Back" and "Next" to the bottom right and move "Return to Home Screen" to where "Back" is.

Alternatively, move "Return to Home Screen" to the bottom of the gray left sidebar. Or right under Upload & Review in the left sidebar. It's an important button - I use it all the time.

**Comment by garrettmflynn** [comment]
The first option sounds good! I've had this thought many times before, we just defaulted to how SODA handled things and never prioritized a change
