### ISSUE TITLE
Undoing Add Row to HandsOnTable has odd behavior

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#592]
A user pressed Cmd-Z repeatedly to try to undo adding a new subject to the subjects table. That moved the selector through the columns until it got to the first one and then the row was deleted. Can we change the behavior of Cmd-Z immediately after adding a row to remove the whole row?

Version: Main branch on Mac M1, 0.0.13 on Mac

**Comment by CodyCBakerPhD** [comment]
Depends on how easy it is to make ctrl-z undo row addition as an action; if tricky, the actual problem is countered by the instructions below every table to double-click to add/remove rows - that text simply needs to be larger and less gray

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
