### ISSUE TITLE
Some Next buttons have confusing text

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#593]
Some of the Next buttons have text:
Generate Data Structure
Request Metadata Schema

These seem to be more confusing than helpful. Can we just make them all "Next"? Or "Next: Specify Source Data", "Next: Specify File Metadata"

**Comment by CodyCBakerPhD** [comment]
Keeping text minimize to "Next" or "Continue" is fine; the tabs on the left and tracker on the top communicate the rest

**Comment by garrettmflynn** [comment]
Got it. I was including alternative text to indicate _what the button accomplishes when pressed_, but we've added some advanced save/update functionality and the user really doesn't need to know that.
