### ISSUE TITLE
Add "Provide feedback" widget?

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#604]
This site https://query.neurobagel.org/ has a little widget on the side for providing feedback without opening a github issue. The code addition seems relatively straightforward: https://docs.appzi.io/install . The neurobagel developer recommended it as an easy way of getting feedback from non-technical users and there is a good free tier.

**Comment by garrettmflynn** [comment]
That's really nice! I'll add this to a PR soon.
