### ISSUE TITLE
Update text and icons on main page and guided mode

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#61]
Since I've assigned #60 and #59 to Ryan, I'll assign the current in-development pages to @garrettmflynn 

Can you update the text and assets for the main page and first couple pages for guided mode to be more NWB-like and less SODA?

I think you had previously done this at some point anyway but maybe it's still split off?

**Comment by garrettmflynn** [comment]
Can do! Yeah there were some updates in #19 that were never merged because of our discussion of documentation methods (i.e. screenshots vs Chromatic) and the changes in #32 that change where the active pages live
