### ISSUE TITLE
[Feature]: Allow Users to Access Human-Readable Changelogs

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#616]
@CodyCBakerPhD and I had an interesting discussion about human-readable changelogs during our last meeting, which prompted some ideas about how to handle change updates for users.

If we enable auto-update, it would be ideal for users to have a narrative description of the latest changes rather than simply encouraged to review the `CHANGELOG.md` file. This could be achieved by a blog on the [NWB GUIDE documentation](https://nwb-guide.readthedocs.io/). 

We also discussed a possible need for [persistent versioning](https://blog.pydantic.dev/blog/), though this seems more like an alternative approach to the blog.

**Comment by CodyCBakerPhD** [comment]
I've also noticed in a lot of other desktop applications, one of the fields in the top selector (place where we usually find the dev console and such) says something about 'view changelog' and they are usually very human readable

**Comment by CodyCBakerPhD** [comment]
This was added as apart of #760
