### ISSUE TITLE
Subject metadata table not deleting rows

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#628]
### Describe the issue

<img width="1025" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/868490c3-7d8d-4858-ba6b-464f83bb94ec">

### Steps to Reproduce

I got this through messing around with deleting rows and going back and forth through the interface. I am unable to proceed

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Can you provide a full set of instructions for how to reproduce the problem you're seeing? I'm unable to reproduce on my end

**Comment by garrettmflynn** [comment]
Same here. I have a hunch this is related to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/510, though I'm not sure from your description above whether you were toggling back and forth between the Locate Data and Subjects pages.

**Comment by bendichter** [comment]
No, tried but I wasn't able to reproduce it. I guess we can just ignore this for now until it comes up again

**Comment by CodyCBakerPhD** [comment]
OK, re-open if you see it again (bonus points if you can provide step-by-step reproducibility using the tutorial data or one of the other testing pipelines)
