### ISSUE TITLE
[Feature]: NWB inspector results unclear

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#635]
### What would you like to see added to the NWB GUIDE?

<img width="1267" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/7a48c056-61f1-4878-8cab-b87759e9156b">

It would not be clear to a user that these are best practice suggestions that can be safely ignored. Could we find some way to indicate their importance? The color is nice but that does not tell us we can ignore them.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
There is a legend on the first pipeline page, and will be a reference page in the tutorial

An on-page legend would also be nice if there's a good place for it

Where on the page would you think such a legend would look nice

**Comment by bendichter** [comment]
<img width="1207" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/5af8ab7b-5d16-4869-8fe6-acaead6c8498">


I think here would be good, just above the bottom bar. The legend could have the 3 or 4 error types aligned horizontally so they don't take up much space in the UI

**Comment by garrettmflynn** [comment]
Partially completed by showing a legend in Guided Mode.
