### ISSUE TITLE
[Feature]: "Embargo status" is confusing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#637]
### What would you like to see added to the NWB GUIDE?

I think the embargo status section of the form is a bit confusing.

1. Can we have a string next to the checkbox that says "embargo this Dandiset"
2. Can you make it so the NIH Award Number text field is inactive by default and becomes active when "embargo this Dandiset" is checked/inactive when unchecked? Also, when it is checked, please add a red asterisk indicating that this field is required.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
@bendichter Is this resolved now?
