### ISSUE TITLE
Form stuck on upload form

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#641]
### Describe the issue

<img width="1137" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/5805269f-0f36-44ba-b31b-74e35592bbcc">

The "Loading form contents..." is stuck and the form never appears. When I go to this screen I had invalid keys, so I input correct keys, but then I got to this screen and the new form never appeared.

### Steps to Reproduce

See above

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by garrettmflynn** [comment]
Figured out how to replicate, and it's silent. Determining the issue now.

**Comment by CodyCBakerPhD** [comment]
Is this on entering that page, or on trying to upload data?

The latter is not expected to work with the current release ATM due to the pydantic v2 issues that are trickling down from DANDI (NeuroConv `main` just recently resolved, working on a PyInstaller resulting from that atm)

**Comment by garrettmflynn** [comment]
As far as I can tell, it's when you visit the page when the api key isn't initially set.

I can cause the current test suite to fail on the E2E tests—though only the DANDI ones, which will fail anyways at the moment.
