### ISSUE TITLE
New dandiset not appearing

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#643]
### Describe the issue

I just added a new Dandiset "213367 — New test". When I start typing, it appears in the dropdown and is selectable, however when I just look at the dropdown with nothing in the text field, this dandiset is not in the list

<img width="1274" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/7d236ef1-a907-4e04-a3b2-635dbebc23e7">

Is it possible that this search result was cached at some point and never updated?

### Steps to Reproduce

See above

### Operating System

OSX

### GUIDE Version

fix-dandi-waiting branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by garrettmflynn** [comment]
Can you create a screen recording similar to the other Issues? I've just tested this and I was able to locate the new Dandiset—so I'm curious if I'll notice anything with your workflow that I missed on my end.

**Comment by bendichter** [comment]
Oh, I see now. Based on the screenshot above, I thought that there were two sections: Main and Staging. There are in fact 4 sections: Drafts - Main, Drafts - Staging, Main, and Staging. Why are we separating the drafts from the non-drafts?

**Comment by garrettmflynn** [comment]
IMO we've been assuming that you won't be uploading to non-drafts from the GUIDE as much—though it's still possible. 

I'm open to removing the distinction. Not sure if we had an explicit discussion on the split before.

**Comment by CodyCBakerPhD** [comment]
We did, but maybe it wasn't written

So here is the justification, though I admit it is more for power users like ourselves that have **dozens** of dandisets that populate here...

While every dandiset technically always has a 'draft' state, if it was published and then not modified, this draft state isn't very useful as a distinction. So the current organization is effectively 'new dandisets' at the top (draft) and 'old dandisets' (published, not wanting to upload any more to) on the bottom.

We could achieve nearly the same visual organization if we order the selector contents by time of last modification, with unmodified dandisets being on the bottom and freshly created ones towards the top?

Likewise, we're not really communicating the detail that if someone uploads to a published dandiset, it 'creates' a fresh draft of the dataset. Though that would become obvious when the come to revisit this selection screen
