### ISSUE TITLE
[Feature]: Upload button

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#647]
### What would you like to see added to the NWB GUIDE?

On this page:

<img width="1278" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/09e44b0b-6804-4a3d-b56e-32495660db2a">

It's not clear that the "Next" button initiates the upload. I think it would be better if we removed the "Next" button and instead had a BIG "Upload" button centered on the bottom half of this page. This size and position of the button will make it clear to the user that this is the definitive upload step and will make the action more satisfying.

<img width="1281" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/d005224f-638f-4a5b-827a-c765d26804bb">

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by bendichter** [comment]
Or we could just change the text of this "Next" button to "Upload"

**Comment by garrettmflynn** [comment]
This is somewhat in conflict with a previous suggestion (https://github.com/NeurodataWithoutBorders/nwb-guide/issues/593) to simplify the text of the buttons to avoid confusion—but I think this particular change is important and the character difference between "Next" and "Upload" is negligible. With the changed location of the button, I'd imagine it's easier to locate visually and the changed text isn't so jarring.
