### ISSUE TITLE
Renamed interfaces revert back to old name

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#649]
### Describe the issue

When you add a new data format any previously renamed formats will revert back to their default name

### Steps to Reproduce

https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/381de37d-ffb5-4d98-b26e-812acafc8911

See the name of the first format in this video. It is renamed to have a 1 at the end and then reverts to its initial name when a new format is added.

### Operating System

osx

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
To confirm, the desired behavior is to maintain any custom changes to the keys and only append `_{index}` to the name of a new selection if one of the current keys shares the same default name?

**Comment by bendichter** [comment]
Yes, exactly
