### ISSUE TITLE
[Feature]: Upload progress bar

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#650]
### What would you like to see added to the NWB GUIDE?

<img width="919" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/5b135836-56d8-46d9-b934-08e9b708d8c7">

Is there a way to create a progress bar so that we can track the progress of uploads? I know we've discussed this before but I wasn't able to find an open issue for it. Apologies if this issue already exists somewhere.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Yes, we know generally how we are going to approach this with https://github.com/catalystneuro/tqdm_publisher but we're still hashing out the exact implementation strategy to be effective at integrating with NWB Inspector (for scanning files), HDMF (for writing files), and DANDI (for uploading files)

**Comment by bendichter** [comment]
OK, that makes sense

**Comment by CodyCBakerPhD** [comment]
This has been added for everything except DANDI since they use a very customized iteration procedure for the entire operation with no easy injection point per worker

Will look into ways of piping the stdout to a little console window as an intermediate solution

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/847

Re-open again whenever this starts active development
