### ISSUE TITLE
Electron Styles Missing

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#67]
After #63, the global styles that were attached to the Dashboard component were no longer included in the Electron build because of inconsistent inclusion between the dev server and the built file. 

Specifically, the dev server includes the CSS while the built file has an adjacent `style.css` file that isn't linked.

To fix this, we will have to conditionally link to the built CSS in the Electron build.

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Can you think of any way this could be tested in the continuous integration?

**Comment by garrettmflynn** [comment]
Not in a straightforward way that I can think of.

Thankfully this isn’t going to be a recurring issue since all styles used
by Vite are in the style.css file. This is a highly predictable
behavior—but an oversight in how I expected the build to behave.

Nothing should fall through the cracks now that the styles from the build
are loaded—and, if this issue crops up another time, we should be able to
understand the cause (e.g. the creation of another CSS file because of
changes in a different file) enough to mitigate it moving forward.
