### ISSUE TITLE
Error with datetime object in Locate Data, Linux version

### ISSUE THREAD

**Issue by iezqrom** [NeurodataWithoutBorders/nwb-guide#672]
### Describe the issue

When adding a folder with date and f-string for getting the date at the Locate Data screen, the API endpoint /locate fails. It seems to be because the DeepDict object stores the date as a datetime object which can't be serialized to JSON format.

![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/42712006/e31025b5-5e37-4508-a4c3-178a00e5a60e)

### Steps to Reproduce

1. Create a new conversation pipeline
2. Check both 'Would you like to locate these sessions programmatically' - Yes
3. Video - VideoInterface format
4. Choose base directory and string path
5. When it tries to automatically list the files, it fails

### Operating System

Ubuntu 20.04.6 LTS

### GUIDE Version

linux-latest

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
@iezqrom I'm having trouble reproducing this

Can you provide the exact f-string used?

If you can record a video of your screen during the process leading up to the error, that also helps tremendously

**Comment by iezqrom** [comment]
This is the f-string:

`Subjects/{subject_id}/{session_start_time:%Y-%m-%d}/{session_id}/raw_video_data/{condition}/{}.mp4`

here's a screenshot of my data structure folder:
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/42712006/194953a1-46f5-43d9-acc6-1271b7af9f1a)

[Video during process leading up to video and console logs](https://drive.google.com/file/d/1ozIEqeBeCqX0KENLXLyH_UB3Gxk9bh-N/view?usp=sharing)

**Comment by CodyCBakerPhD** [comment]
@iezqrom OK, we've fixed the issue in #686 

We'll evaluate how soon we can cut another stable release with this fix - otherwise to get the feature you would need to return to the `linux-dev` branch once it gets merged, just be aware that there might be more bugs than there are on the last release

**Comment by iezqrom** [comment]
Great! Glad this helped. I'm watching pull requests so hopefully I can see when you PR to the `linux-latest` branch (:

**Comment by CodyCBakerPhD** [comment]
@iezqrom The new `latest-linux` branch (equivalent to `linux-v0.15.0`) has been released with this fix included!
