### ISSUE TITLE
[Bug] support for PhySortingExtractor Exclude Cluster Groups

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#681]
### Describe the issue

Now, in the dev branch, I get this for Phy

<img width="984" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/4734149f-c975-454a-8005-2ce867d7884c">

However, I am using the main branch of NeuroConv and the source schema for Phy is:

```python
PhySortingInterface.get_source_schema()


{'required': ['folder_path'],
 'properties': {'folder_path': {'format': 'directory', 'type': 'string'},
  'exclude_cluster_groups': {'type': 'array', 'items': {'type': 'string'}},
  'verbose': {'type': 'boolean', 'default': True}},
 'type': 'object',
 'additionalProperties': False}
```

I don't think this internal schema is improper- GUIDE should be able to render it.

### Steps to Reproduce

see above

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
@bendichter I'd suggest refreshing your environment and all that

This worked fine for me today

**Comment by bendichter** [comment]
ok, I'll try that

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn While the original issue was fixed, I do not see items added to the list on current `main`


https://github.com/NeurodataWithoutBorders/nwb-guide/assets/51133164/c072f387-0e1b-4b9d-bcb5-b672c4ab8814

**Comment by CodyCBakerPhD** [comment]
Error from console:

```javascript
List.ts:256 Uncaught (in promise) TypeError: Cannot create property 'originalKey' on string 'mua'
    at #renderListItem (List.ts:256:35)
    at Array.map (<anonymous>)
    at List.render (List.ts:437:51)
    at List.update (lit-element.ts:160:24)
    at List.performUpdate (reactive-element.ts:1329:14)
    at List.scheduleUpdate (reactive-element.ts:1261:17)
    at List.__enqueueUpdate (reactive-element.ts:1233:25)
```
