### ISSUE TITLE
[Feature]: Duration picker

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#682]
### What would you like to see added to the NWB GUIDE?

Right now, entering in the age of the subject requires that the user knows or learns ISO 8601 duration format.

<img width="754" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/465a1b0b-050b-462c-9416-9645ac73aeaf">

Would it be possible to user a duration selector widget that is more intuitive? Does such a picker already exist?

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by garrettmflynn** [comment]
Do you have an example of such a picker? And wouldn't the user need to know the DOB for this to happen anyways (e.g. calculate the ISO 8601 duration from the DOB and current date)?

**Comment by CodyCBakerPhD** [comment]
> And wouldn't the user need to know the DOB for this to happen anyways 

Not exactly; the point is the difference in resolution. Sometimes they might just say `P3W` without being more specific, which doesn't require knowing the exact DOB as an ISO date (regardless of time) and doing the math against the session start date

There's also educating people about the duration range syntax `P3W/P5W` meaning they don't know the exact age either, but know it's within that range



> Do you have an example of such a picker, possibly from a different application?

I've never seen a picker for this, but I'm fairly sure any time I've seen something similar, each field of the page is separated as a different entry on a web form

That is,

```
Age

Years: 
Months:
Days:

Hours:
Minutes:
Seconds:
```

with pretty much all fields being optional, but at least one entry required

But this feels like it takes more typing than the ISO string, while requiring less reading of tooltips to learn/understand what ISO 8601 is, so there's the tradeoff

Also seems less copy/pastable

**Comment by CodyCBakerPhD** [comment]
Maybe the 'add subject' button could trigger a popup that collects the information in a user friendly way, but the values on the table still show up as they do (and are still copy/pastable that way)?

And the user friendly form could have a yes/no toggle of if they want to submit age OR date of birth, finally alleviating that confusion by not displaying both and validating both together

**Comment by garrettmflynn** [comment]
Ah gotcha. We could also have a nested table form that provides the form described above as a pop-up for Age.

**Comment by garrettmflynn** [comment]
> And the user friendly form could have a yes/no toggle of if they want to submit age OR date of birth, finally alleviating that confusion by not displaying both and validating both together

You're right, though, this is an issue with the Table format in general

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
