### ISSUE TITLE
[Feature]: Pipeline workflow page design

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#683]
### What would you like to see added to the NWB GUIDE?

<img width="1011" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/8dbc8d1a-3d26-494b-b298-6d8edd86d94c">

We are not locating sessions, we are locating files. I would change "Would you like to locate these sessions programmatically?" to "Would you like to locate the source data programmatically?" I think this might be a bit clearer.

I would also remove the Session Workflow sectioning. I can see how that would be useful if we have multiple types of workflow settings, but as it stands now it's just extra organizational information that does not really convey anything meaningful to the user.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
> I would also remove the Session Workflow sectioning.

What do you mean by this?

**Comment by bendichter** [comment]
I think the form should be removed from the black rectangle that has the "Session Workflow" heading.
