### ISSUE TITLE
Unable to define subject_id and session_id in single-session mode

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#689]
### Describe the issue

I have no way of indicating the session_id or subject_id in the single-session mode. The GUIDE just assumes that it is Subject 001 and Session 1 even though I don't specify that anywhere.

### Steps to Reproduce

n.a.

### Operating System

osx

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Ah, right. Because those were removed from file metadata when the table was added

Should we add those back into the file metadata? Or unlock the session/subject table but have a more complicated table functionality that prevents the user from adding new subjects and new sessions?

**Comment by garrettmflynn** [comment]
This was the default behavior of the GUIDE when the user selected not to locate their sessions programmatically on the Locate Data page.

Both the session and subject ID were previously editable using the Subjects Table—but we've hidden this from view if the user doesn't have many sessions.

As Cody mentioned, we have a few options. 
1. Limit the subject table for editing a single subject + session combination.
2. Re-enable the ID properties on the File Metadata page
    - However, this solution breaks the linear flow that was previously established by using the Subjects Table as the single point where IDs were edited. We'd have to re-write a bit of the pipeline to transform the default IDs into the user-defined IDs before sending to the server for conversion.

**Comment by CodyCBakerPhD** [comment]
Or, how about, on the pre-form page

If it is determined from response "no" to multi session, have a one-time input form for both subject ID and session ID?

**Comment by garrettmflynn** [comment]
Yeah, that also works!
