### ISSUE TITLE
[Feature]: Add page after conversion before upload that says your data has been converted and where

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#702]
### What would you like to see added to the NWB GUIDE?

A user may not want to upload their converted data immediately to DANDI. Perhaps they are interested only in conversion so that they can run an analysis on the NWB file, or they want to append trials or other custom data through pynwb/matnwb to the NWB file. Currently after conversion, they are prompted to enter DANDI API keys if they haven't entered them yet and then asked to upload the data to DANDI. They do not know where their converted files are unless they explored the Settings.

I think it would be useful to add an informational page after conversion and before upload that says something like:

"Success! Your data has been converted to NWB. You can access the NWB files at [path]. 

If you are ready to upload your NWB files to the DANDI Archive, press **Next**. If not, press **Exit Current Pipeline** to return to the main page. You can always return to this pipeline to upload these NWB files to DANDI."

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
An early preform could also ask if they want to upload to DANDI immediately and decide what should be the final page based on that
