### ISSUE TITLE
C elegans sex validation does not allow XO/XX

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#703]
### Describe the issue

The sex field for C elegans is an odd edge case that doesn't seem to work correctly right now. XO and XX should be allowed when the species is set as C elegans. 

### Steps to Reproduce

https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/dc07c255-bb3c-46e8-b908-7308d9421d02

### Operating System

Mac M1

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
fixed in #705
