### ISSUE TITLE
Should a 'project' span multiple types of experiments?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#71]
Right now we create what we call 'pipelines' and we have one of those for every 'project'

A single 'pipeline' corresponds to a single `NWBConverter` class which corresponds to a single unique experimental setup, and will eventually be able to run on multiple sessions that follow the same setup

We were originally envisioning a 'project' as being equivalent to a DANDI set, so it could have multiple types of experiments, but maybe this isn't the best design and instead would be better for the GUIDE to simply have a flat collection of pipelines, and how they map onto particular DANDI sets is only a consideration during the final optional stage of 'upload to DANDI'

**Comment by bendichter** [comment]
I think we should start without different experiments in GUIDE for now. We might want to add them later but they shouldn't be part of the MVP. Once we get some user feedback we can assess whether it would be worth the effort
