### ISSUE TITLE
Error: This meta file version of spikeglx is not implemented

### ISSUE THREAD

**Issue by zhiwen10** [NeurodataWithoutBorders/nwb-guide#713]
### Describe the issue

Hi. Thank you for building an interface that is easy to use for conversion to NWB format. This is the most intuitive version I can find out there. 

I am attempting to convert SpikeGLX recording with both "ap.bin" and "lf.bin" into a single .nwb file, which I managed to create without problem in the example dataset that comes with the tool.
However, when I tried to convert my own data, I encountered an error message in the Source Data Information stage:
`This meta file version of spikeglx is not implemented`

I tried to change "appVersion" from 20201024 to 20190327 manually inside the meta file, without success.
Any ideas how to fix this? 
(Changed '.meta' extension to '.txt' extension in attached files to comply with github file format policy. )

![NWB_guide_error](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/24544991/631538ec-e401-49d3-a71b-0438c916e56e)
[p1_g0_t0.imec0.ap.txt](https://github.com/NeurodataWithoutBorders/nwb-guide/files/14818844/p1_g0_t0.imec0.ap.txt)
[p1_g0_t0.imec0.lf.txt](https://github.com/NeurodataWithoutBorders/nwb-guide/files/14818845/p1_g0_t0.imec0.lf.txt)

### Steps to Reproduce

Error: This meta file version of spikeglx is not implemented

### Operating System

windows 10

### GUIDE Version

0.0.14

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Hello and welcome!

I was able to replicate the issue simply by modifying the `imDatPrb_type` field of the `.meta` file in the generated tutorial data and setting it equal to your value (`1100`), which apparently has not been seen before

I have opened https://github.com/NeuralEnsemble/python-neo/issues/1451 upstream to request support for this

Is there anything else to know about this probe? Is it known by other names (such as the the other ones known to us [seen here](https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglx_utils.py#L100-L104))

**Comment by zhiwen10** [comment]
Thank you very much for your prompt response. Indeed, this is a version of probe ([NP Ultra](https://pubmed.ncbi.nlm.nih.gov/37662298/)) that is not publicly available yet, but soon will be hopefully. 

It has 384 active sites as you noticed (but high dense, smaller site-to-site distance), which is also programmable in some variants. It is supported by spikeGLX 2023 onward versions at least.

I'm unsure what specific properties are relevant for the conversation purposes, but the majorities are close to other single-shank probes.

**Comment by CodyCBakerPhD** [comment]
Lovely, this is the first request we've had for Ultra support, though we've heard it about it from the SpikeGLX team for the last year

Since this is the first case we've seen, would you mind sharing a small example session so we can add it to our testing infrastructure? (google drive, dropbox, etc. is fine. Feel free to email at cody.baker@catalystneuro.com if you want to keep it private access)

**Comment by zhiwen10** [comment]
I'll get back to you on this, once I converted my data successfully. For now, I'm just gonna change `imDatPrb_type` field of the `.meta file` to `"0"` as "NP 1.0".

**Comment by CodyCBakerPhD** [comment]
Please at least include a description or modify the ecephys `Device` name to indicate your correct probe type - there's a lot of metadata that gets set based of that file value and while simply changing it will 'make it work' it will result in some incorrect metadata assigned to the representation in the NWB  file that could throw off meta-analyses on DANDI

**Comment by zhiwen10** [comment]
Will do. Thank you

**Comment by CodyCBakerPhD** [comment]
Looking more into this, I can't recommend pretending that this is NP1 because a lot of probe metadata (channel locations) look like they will be very wrong with respect to this new meta file

Does the `.bin` have the same structure? (int16 data type, shape of frames x 384) If so we can just use your meta files to mimic some testing data - but again, we'd really prefer to have an actual real example of what the data looks like so add support for it

**Comment by zhiwen10** [comment]
That makes sense. The channel maps are different, but the .bin data have the same structure. I imagine the bin. data don't get reorganized based on the channel map? I planned to test the .NWB data with kilosort to make sure the data is in the right arrangement as expected, but much better if you can provide support before it happens. I'll prepare a small dataset with priority and send to your email today.

**Comment by CodyCBakerPhD** [comment]
Just an update: I heard from Alessio recently that they plan to get this released upstream in early May

Neo PR started: https://github.com/NeuralEnsemble/python-neo/pull/1459

**Comment by CodyCBakerPhD** [comment]
Looks like this was pushed through in the last couple of months!
