### ISSUE TITLE
Ecephys is not allowed to have the additional property "Units".

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#716]
### Describe the issue

On the testing pipeline named "SpikeGLX V1 SingleProbe AP", on the "File Metadata" page, everything is either yellow or green, but clicking "Next" results in a popup error that says `Ecephys is not allowed to have the additional property "Units".`

### Steps to Reproduce

^

### Operating System

Mac M1

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
I can replicate this as well

```javascript
Uncaught (in promise) Error: Ecephys is not allowed to have the additional property "Units".
    at JSONSchemaForm.throw (JSONSchemaForm.js:500:15)
    at JSONSchemaForm.validate (JSONSchemaForm.js:567:38)
    at async GuidedFooter.onNext [as __onNext] (GuidedMetadata.js:182:46)
```
