### ISSUE TITLE
[Bug] Ophys metadata schema

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#738]
### Describe the issue

Using a built version (particularly the current draft of 0.0.15 on Windows) but don't know if it's problem on dev (assuming it is)

Make a new pipeline, and select a single data format (Bruker single tiff)

Specify the GIN file `.../ophys_testing_data/imaging_datasets/BrukerTif/NCCR32_2023_02_20_Into_the_void_t_series_baseline-000`

Proceed to metadata customization page, fill everything in and try to proceed

### Steps to Reproduce

index-b8682a56.js:57040 Uncaught (in promise) Error: Ophys requires property "definitions".
    at JSONSchemaForm.throw (index-b8682a56.js:57040:11)
    at JSONSchemaForm.validate (index-b8682a56.js:57087:19)
    at async GuidedFooter.onNext [as __onNext] (index-b8682a56.js:182993:9)

### Operating System

Windows

### GUIDE Version

0.0.15

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
After this one we can probably cut a release

**Comment by garrettmflynn** [comment]
This has a fairly simple cause. Definitions should not exist on the JSON Schema properties itself but one level lower: https://json-schema.org/understanding-json-schema/structuring#bundling

Looks like something is wrong with the `BrukerTiffSinglePlaneConverter` schema.

**Comment by CodyCBakerPhD** [comment]
This has been patched locally and official solution in progress on NeuroConv
