### ISSUE TITLE
[Enhancement]: Change "File Path" header to "Path to SpikeGLX ap.bin or lf.bin file"

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#748]
### What would you like to see added to the NWB GUIDE?

On the source data page for SpikeGLX Converter and Recording, there is a description below the file selector box:
<img width="984" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/3764d358-209f-4e16-8079-5898ee3e9cdf">

In my personal experience and experience observing the user tests, people click the box and are briefly confused before reading the smaller gray text below the box (and sometimes they don't even read that text - the gray makes it look like it is not particularly important and the fact that it is after the box suggests it is not relevant to the action of clicking the box). The headers "Folder Path" and "File Path" are generic and not very useful. I suggest that if the description exists, it replaces the header instead of being text after the box, or there is a new field per interface that provides a more descriptive replacement of the header. This affects only the handful of interfaces that have a description.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by rly** [comment]
In general, I wonder whether the gray description should be moved above the text box / input field.

**Comment by CodyCBakerPhD** [comment]
These were all updated on the NeuroConv side
