### ISSUE TITLE
The dashes at the top of the page allow users to skip ahead

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#749]
### Describe the issue

Near the top of each page, there are a few clickable colored dashes that represent the subsections in the current section, just like in the left sidebar.

<img width="1255" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/e800e88e-ebe0-41d7-8b01-7f19506279bf">

These dashes are clickable and allow the user to skip ahead and enter weird states

<img width="1249" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/5b9db976-16e6-41c8-91fc-721429429f39">

The subsections in the left sidebar are not clickable until you do the subsections before. That makes sense.

Given that we have the left sidebar tracking pipeline progress, I think the top dashes do not add value, add clutter/questions, and can be removed.

The top menu is also redundant with the left sidebar. I could go either way on whether we should remove that, but for now I lean toward suggesting we keep it. 

### Steps to Reproduce

n/a

### Operating System

Mac M1

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
> Given that we have the left sidebar tracking pipeline progress, I think the top dashes do not add value, add clutter/questions, and can be removed.

Many user testers requested specifically that those pills be clickable

**Comment by CodyCBakerPhD** [comment]
> The top menu is also redundant with the left sidebar. I could go either way on whether we should remove that, but for now I lean toward suggesting we keep it.

Pretty sure I remember TurboTax also has a similar nav for reference through a workflow, though that also is for the case where a single step of the left sidebar has multiple 'inner' steps

**Comment by garrettmflynn** [comment]
I agree that these are redundant. These are all holdover SODA components, so we might just want to remove and double-down on improvements to the tree representation—which would also remove synchronization overhead.

**Comment by CodyCBakerPhD** [comment]
Have these been removed yet?

**Comment by garrettmflynn** [comment]
Not yet, though it's very simple. Just wanted confirmation that we agreed on this change

**Comment by CodyCBakerPhD** [comment]
removed in #781
