### ISSUE TITLE
Interface Selection

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#75]
Opening this discussion regarding the optimal UX design for selection interfaces

Right now the temporary stand-in is a basic mutli-select form

Eventually a search-like functionality would be great, as long as the default (empty search) is a full listing of available interfaces ordered in a fashion that 'makes sense' (modality -> technique split is pretty intuitive for this, but open to others)

The bigger question is, is the user adding one interface per selection?

How do they know when they might need multiple copies of a single interface to match different source data? 

What does it look like as the user adds more and more interfaces to their list?

**Comment by CodyCBakerPhD** [comment]
Also, and I've seen many cases of this in past weeks - but how can we best communicate to the user what that constitutes an interface for their format?

In some cases they might say they used system XYZ  to perform the recordings and saved the data in format ABC, but then they modify the files in some way which breaks the official format, but nonetheless they might claim their data to be in ABC by selecting the ABCInterface, when in actuality they should have chosen some other option

**Comment by garrettmflynn** [comment]
These are all really important questions! 

Are there any useful heuristics for what formats are associated with what files (e.g. file naming conventions, standard extensions, etc.)? 

## Choosing the Correct Interface
The first thing that comes to mind would be to sort / search by file types, which is much more immediate than a type (e.g. maybe I'm naive about whether I have SpikeGLX data, but I do have lf.bin files...so I wonder what I can do with those).

If provided a directory, we could also do a quick-and-dirty search where we try to auto-assign interfaces—though I'm not sure I'm the right person to understand all the complexities with that option. 

## Adding Duplicate Interfaces
Generally, I'd want to maintain an editable list of chosen interfaces that were selected through the search component. The Figma document has this represented on the Define your Data Formats page.

This list would directly represent the dictionary passed to initialize the NWBConverter, where keys are arbitrary and values ultimately resolve to the actual Interface class. 

Based on my conversations with Ben, the key for each list item would default to the DataInterface name (without "Interface") and could be clicked and edited by the user to whatever they'd like. I'd assume duplicates can just have an incrementor added at the end of the key.

**Comment by CodyCBakerPhD** [comment]
> Are there any useful heuristics for what formats are associated with what files (e.g. file naming conventions, standard extensions, etc.)?

Yes, there absolutely are - we'll work on adding those to NeuroConv like we did for the interface keywords


> If provided a directory, we could also do a quick-and-dirty search where we try to auto-assign interfaces—though I'm not sure I'm the right person to understand all the complexities with that option.

I'm optimistic this can be done at some point but for now its deemed an advanced feature and not a requirement


> Based on my conversations with Ben, the key for each list item would default to the DataInterface name (without "Interface") and could be clicked and edited by the user to whatever they'd like. I'd assume duplicates can just have an incrementor added at the end of the key.

Yes, exactly, and a 'plus' button that triggers selection of a new interface to the running dictionary

Though we did discuss maybe hiding the keys of that dictionary unless there is a duplicate of at least one interface, and then autogenerate default keys as you say with an incrementer

One reason to still allow these keys to be editable could be for multiple processing interfaces (sorting for now) - it's not uncommon to want to write one version of the sorting data that was uncurated and a another version that was, where both are stored in the same format

**Comment by CodyCBakerPhD** [comment]
@garrettmflynn Could you try implementing those ideas in #34?

**Comment by garrettmflynn** [comment]
Been updating #34 with some updates. Here's what's been done so far:
1. Autogenerate default keys
2. Autogenerate incremented keys when duplicates are present
3. Allow editing keys when clicked
4. Show all options when empty
5. Show the search after the user presses a button to indicate they want to add more

Is there anything else you'd like me to implement? Otherwise it would be great to get your feedback on the current iteration.

**Comment by CodyCBakerPhD** [comment]
It's looking great so far, some final comments on the respective PR

**Comment by CodyCBakerPhD** [comment]
Solved in #34
