### ISSUE TITLE
[Feature]: Change "Create a Dandiset" Archive and License selectors to radio button? 

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#761]
### What would you like to see added to the NWB GUIDE?

Minor UI QoL suggestion. On the Create a Dandiset page:
![image](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/310197/2be9f672-68cf-4e38-baf6-1c6a970a95b5)

Clicking the Archive text field opens a dropdown with options "Development Server" and "Main Archive". I then click to select one. Do we expect there to be additional options? Currently if I want to change the option, I have to click the text field and delete all the text to see the other option. If there are only two options, a radio button may be better. With a radio button, it would also be one fewer click to select one. The dropdown allows search and custom values but I think that is not necessary here and provides room for user error, e.g., if they type an invalid value.

Similarly for License. There are only two options and I have not heard from DANDI about possibly expanding that.

(I know DANDI wants to support distributed archives eventually, such as those that run on institutional servers, but I think that is a longer-term feature and would require more fields to specify than a dropdown option.)

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
