### ISSUE TITLE
[Docs]: Increase space around version switcher box

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#779]
### What would you like to see added to the NWB GUIDE?

From https://github.com/NeurodataWithoutBorders/nwb-guide/pull/763#issuecomment-2078954693

> IMO, more space to the left of the box, maybe 15-20px. Remove the border. Dropdown open/close on hover is not necessary. Super minor!

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by garrettmflynn** [comment]
Was able to sneak the hover behavior in too!
