### ISSUE TITLE
[MVP] Better progress bar for single session

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#80]
This might get a little tricky as per previous conversations, but putting it on the eventual to-do list with low priority initially

It just wouldn't be a very nice experience if the user tries to run a conversion of a file that's > 10 GB and then the app just freezes for an indeterminate amount of time

Existing progress bars already exist under the hood via `tqdm`, but unclear how to pipe that out in real time asynchronously to the front-end

**Comment by bendichter** [comment]
For 2, I guess we could do something like:

```python
# on the GUIDE backend

def update_display()
    ...


SpikeGLXRecordingInterface.run_conversion(
    ...,
    iter_opts=dict(reporthook=update_display),
)
```

`reporthook` is borrowed from [urlretrieve syntax](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve)

We could modify [`GenericDataChunkIterator`](https://github.com/hdmf-dev/hdmf/blob/963aea736d1b1fe383707aec293c93860771b3a2/src/hdmf/data_utils.py#L133) either on the hdmf side or the NeuroConv side to have a `reporthook` as an optional kwarg in `__init__` which, if provided, is called every iteration with the `GenericDataChunkIterator`'s self as the sole input.

This function would then be automatically passed through the unpacking of `iterator_ops` e.g. [here](https://github.com/catalystneuro/neuroconv/blob/1357319ffe454fda82824dfec6af6d0f2854ed3f/src/neuroconv/tools/spikeinterface/spikeinterface.py#L493-L498):

```python
traces_as_iterator = SpikeInterfaceRecordingDataChunkIterator(
    recording=recording,
    segment_index=segment_index,
    return_scaled=return_scaled,
    **iterator_opts,
)
```
