### ISSUE TITLE
[Feature]: Warn of Inconsistent Age and DOB

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#805]
### What would you like to see added to the NWB GUIDE?

It would be great to let users know if they have inconsistent `Subject.age` and `subject.date_of_birth` values. 

This _could_ be implemented by the NWB Inspector, but my understanding is that this only implements checks at a single parent (e.g. `NWBFile`, `Subject`, etc.) level. And this feature would require some extrapolation between `NWBFile.session_start_time`, `Subject.age`, and `subject.date_of_birth`—aside from some very coarse checks using the current date.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
