### ISSUE TITLE
[Feature]: Remove Distinction between Warnings and Errors

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#807]
### What would you like to see added to the NWB GUIDE?

Based on our team discussion of the Dev Hackathon results, we determined it would be useful to remove the distinction between _warnings_ and _errors_ on the GUIDE. This will help reduce the user's cognitive load and increase their adherence to Best Practices.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Summarized and moved to https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846

Re-open again whenever this starts active development
