### ISSUE TITLE
[Feature]: Ensure Human-Readable Validation Messages

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwb-guide#812]
### What would you like to see added to the NWB GUIDE?

The messages rendered from the NWB Inspector should clearly indicate how to update the GUIDE to resolve the issue. In particular, the Institution and Keywords messages are not the simplest to understand—though it is technically possible to identify where to look from the message.

<img width="708" alt="Screenshot 2024-05-29 at 2 14 50 PM" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/46533749/0da28c49-7ae5-45fa-9b0d-eb344acd37e7">

We should come up with a robust strategy for providing GUIDE-side recommendations—or simply tweaking the rendering—so users are presented with clear instructions when certain issues like this come up.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
The easiest thing for us to do would probably be a rewrite of Inspector messages to indicate how to fix them with lower cognitive burden
