### ISSUE TITLE
Project Name required field

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#82]
![image](https://user-images.githubusercontent.com/844306/228080587-59d66daf-8a80-4a0d-844d-cccd8a5d0089.png)

Use a red asterisk to indicate that Project Name is required

**Comment by CodyCBakerPhD** [comment]
I believe this is fixed now

![image](https://user-images.githubusercontent.com/51133164/230118549-a0acacb6-4bb4-4466-94de-3992dedffce5.png)

If it's not on your system feel free to re-open
