### ISSUE TITLE
`Enable` button for data interface appears inactive 

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwb-guide#853]
### Describe the issue

When selecting the ``Skip`` button for a data interface: 

![Screen Shot 2024-06-10 at 1 29 39 PM](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/10999845/6ddc3448-91ff-476b-a998-1bd90c33febd)

The entire row, including the button to ``Enable`` is shaded as disabled: 

![Screen Shot 2024-06-10 at 1 29 45 PM](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/10999845/20fa54ca-bd68-4a5a-ae25-5278b3dc1f68)

The ``Enable`` button still works, i.e., I can click the button and the interface becomes active again. So this is just a minor issue with the visual display that makes the button look like it is not active. 

### Steps to Reproduce

Create a conversion pipeline, add a data interface and then select skip when entering the metadata for that interface. 

### Operating System

MacOS

### GUIDE Version

1.0

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Thanks, good catch

Added to #846, not sure we'll be able to solve this in the next few days
