### ISSUE TITLE
DLC conversion not working

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#875]
### Describe the issue

<img width="1276" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/02a1bf25-4678-42e0-bcfa-62f3e08aea94">

When you try to open the DLC files, you get this error:

```
Request Failed
namespace file '/Applications/NWB GUIDE.app/Contents/Resources/spec/ndx-pose.namespace.yaml' not found
```

### Steps to Reproduce

Try to convert our example DLC data

### Operating System

OSX

### GUIDE Version

1.0.1

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Looks like a problem in the build, trying to isolate (we even `collect_all` on `ndx-pose` in the spec file)

Works fine in dev mode however

**Comment by bendichter** [comment]
thanks for looking into this, @CodyCBakerPhD ! Good to know it's working on dev.
