### ISSUE TITLE
MEARec not working in prod

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#879]
### Describe the issue

<img width="1273" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/9d53563d-8df2-4e8a-8d1a-cc2f5345654e">

### Steps to Reproduce

Try to convert from our example data

### Operating System

osx

### GUIDE Version

1.0.1

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
closed by #880
