### ISSUE TITLE
NeuroScope sorting broken when .xml file not provided

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#881]
### Describe the issue

NeuoScope is broken when xml is not provided.

<img width="1276" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/b4e05ae3-402d-4ef3-a521-dc1d53e6b91a">

The xml is in the proper place

<img width="494" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/199c4885-ac4d-4234-bcaa-79803bb92b1a">

The work-around here is to simply provide the xml file.

### Steps to Reproduce

see above

### Operating System

osx

### GUIDE Version

1.0.1

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
This is a NeuroConv-side issue: https://github.com/catalystneuro/neuroconv/pull/926
