### ISSUE TITLE
spike2 recording interface not working

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#882]
### Describe the issue

<img width="1275" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/4082ad31-c996-42ee-94e1-c40181d53691">

### Steps to Reproduce

see above

### Operating System

osx

### GUIDE Version

1.0.1

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
NeuroConv does not support `.smr`: https://catalystneuro.github.io/format-support-table/?tab=ecepys-recording

Only `.smrx`

Just need to adjust the description and suffixes to indicate that

**Comment by CodyCBakerPhD** [comment]
Updated in https://github.com/catalystneuro/neuroconv/pull/925
