### ISSUE TITLE
NWB Guide Documentation lists Stable as Unstable 

### ISSUE THREAD

**Issue by tabedzki** [NeurodataWithoutBorders/nwb-guide#885]
### Describe the issue

NWB Guide Documentation lists Stable as Unstable 
https://nwb-guide.readthedocs.io/en/stable/

"This is documentation for an unstable development version.[Switch to stable version](https://nwb-guide.readthedocs.io/en/v1.0.1/index.html)"

### Steps to Reproduce

Visit https://nwb-guide.readthedocs.io/en/stable/

### Operating System

Any

### GUIDE Version

101 and stable

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Thanks for the report! We noticed this a while back too, I think I know what might be up - will try to fix in upcoming v1.0.2 bug fix release

**Comment by tabedzki** [comment]
Wonderful to hear!

**Comment by CodyCBakerPhD** [comment]
Looks like our suspicions were correct: #886 seems to have fixed this!
