### ISSUE TITLE
Kilosort import syntax errors don't specify filename

### ISSUE THREAD

**Issue by dhmjhu** [NeurodataWithoutBorders/nwb-guide#890]
### Describe the issue

When trying to import Kilosort data, syntax errors in `params.py` refer to `<string>` instead of a real filename.

Trying to import a Kilosort directory with an invalid `params.py` leads to a message like:
> **Request Failed**
> invalid syntax (, line 3)

![Screenshot of error message](https://github.com/NeurodataWithoutBorders/nwb-guide/assets/166628128/e5c52c01-1b2f-4f89-876d-9e076ee28806)

The above message was not properly escaped (see #889). It should say:
> **Request Failed**
> invalid syntax (\<string\>, line 3)

It would be helpful if the filename containing the syntax error could be displayed instead of `<string>`. This may affect other formats, but I've only tried it with Kilosort.

### Steps to Reproduce

1. Add a syntax error to an existing Kilosort `params.py` or use [`guide-error-example.zip`](https://github.com/user-attachments/files/16073819/guide-error-example.zip)
2. Create a new conversion pipeline with a "KiloSort Sorting" source format
3. Select the directory containing the invalid `params.py` and click "Next"

### Operating System

Windows 11 23H2 Enterprise

### GUIDE Version

1.0.2

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
> It would be helpful if the filename containing the syntax error could be displayed instead of <string>. This may affect other formats, but I've only tried it with Kilosort.

This would be helpful, but is not something we would implement on the GUIDE but rather NeuroConv; we have some refactors to source schemas there over the next few months that should make these types of errors a bit more explicit

**Comment by CodyCBakerPhD** [comment]
Closing for now - once NeuroConv makes these kinds of file assertions, a rebuild of GUIDE should automatically forward them to the visual display
