### ISSUE TITLE
License option on "Create Dandiset" form missing asterisk to indicate it is required

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#903]
### Describe the issue

<img width="474" alt="image" src="https://github.com/user-attachments/assets/f186c07d-3678-453c-abac-f19241e07c17">

The description also suggests you can select a **set** of licenses when you can only select one here. The [dandi schema suggests](https://github.com/dandi/dandi-schema/blob/be57e138505819a46475f8f5a590e6f6b00cd1b2/dandischema/models.py#L1503-L1509) you can provide more than one but I think 1) most users would not do that and 2) it would be super confusing given these two options. So we should continue allowing only one.

### Steps to Reproduce

Create a dandiset with UI

### Operating System

Mac OS with Mac M1

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Just reminding about https://github.com/NeurodataWithoutBorders/nwb-guide/issues/761 from the [compilation list](https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846) (item 2.d) since it kind of relates and we do have a radio button now
