### ISSUE TITLE
[Feature]: Add metadata to Dandiset and DANDI Assets

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#905]
### What would you like to see added to the NWB GUIDE?

Assets have metadata that indicate how they are generated and what software is associated with the files. It would be great to add NWB GUIDE, which would help us track the usage of this app and provide better provenance for those assets.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

Yes

### Did you confirm this feature was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Added to compilation of improvements https://github.com/NeurodataWithoutBorders/nwb-guide/issues/846, item 1.g

**Comment by bendichter** [comment]
Hint: This is how the DANDI CLI does it:

https://github.com/dandi/dandi-cli/blob/44e097f9fcc3498b7fb4330e2a1974af79fd9624/dandi/metadata/util.py#L850-L866

https://github.com/dandi/dandi-cli/blob/44e097f9fcc3498b7fb4330e2a1974af79fd9624/dandi/metadata/core.py#L60-L62
