### ISSUE TITLE
Error uploading data

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#922]
### Describe the issue

<img width="1482" alt="image" src="https://github.com/user-attachments/assets/77aad5c2-748d-4809-be23-bbf5db0e87e0">

### Steps to Reproduce

Try to upload any NWB files

### Operating System

OSX

### GUIDE Version

1.0.3

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by bendichter** [comment]
@CodyCBakerPhD any idea what might be going on here?

**Comment by CodyCBakerPhD** [comment]
Resurgence of #426, with related #540 

This is a very annoying one. It never shows up in dev mode, only in builds. E2E tests include live services like DANDI upload but they have to run in dev mode

Source of issue is some interaction between `joblib` from [`dandi.organize`](https://github.com/dandi/dandi-cli/blame/master/dandi/organize.py#L868) and the PyInstaller build. No one knows exactly why that happens but it's been seen multiple times

We thought we fixed this a long time ago by rerouting the call to `joblib.Parallel` via https://github.com/dandi/dandi-cli/pull/1341 but for some reason that reroute seems to now be ignored

I will investigate further

**Comment by CodyCBakerPhD** [comment]
Found the source and fixed in #923
