### ISSUE TITLE
license metadata populated incorrectly

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#943]
### Describe the issue

When you create a new dandiset, the license metadata is created incorrectly

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/c37e7d68-36c1-47bf-9ebe-d8f270d73f0f">

It should be sent as a list with one element, but it is sent as a string, so the API instead breaks up the string and has a license for each letter.

### Steps to Reproduce

Just go through the GUIDE tutorial and create a new dandiset on staging

### Operating System

OSX

### GUIDE Version

1.0.4

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by bendichter** [comment]
@rly do you think you could look into this?

**Comment by rly** [comment]
Does it make sense to have both a dandiset with both CC-BY-4.0 and CC0-1.0? DANDI allows both 
<img width="282" alt="image" src="https://github.com/user-attachments/assets/8327de8c-e1be-4aea-94d8-26f1106b3ca4">
see https://gui-staging.dandiarchive.org/dandiset/213889/draft

We could allow both, but if that's a bug or it is not a recommended practice to have both, we could require the user to select only one.

**Comment by oruebel** [comment]
> Does it make sense to have a dandiset with both CC-BY-4.0 and CC0-1.0? DANDI allows both

Looking at the DANDI page, it seems like it may be intentionally allowing multiple licenses. I'd ping DANDI for clarification.

**Comment by rly** [comment]
Satra wrote: "this was set to allow modeling for a use case of dandisets with mixed assets, but in general only one should be chosen for a dandiset."

For NWB GUIDE purposes, I think limiting the license selection to one makes sense. (Otherwise, I would make the license selector a multi-select.)

**Comment by rly** [comment]
See https://github.com/NeurodataWithoutBorders/nwb-guide/pull/904 for the change that broke this.

**Comment by bendichter** [comment]
It's fine to only allow one, but I think it needs to be passed as a list of length 1
