### ISSUE TITLE
installation on linux - linux-latest branch

### ISSUE THREAD

**Issue by magland** [NeurodataWithoutBorders/nwb-guide#945]
I'd like to install NWB GUIDE on Linux. The installation instructions say to clone the [linux-latest](https://github.com/neurodatawithoutborders/nwb-guide/tree/linux-latest/) branch but that is 281 commits behind main. What's the recommended route?

**Comment by rly** [comment]
Sorry for the confusion @magland. Please clone the linux-dev branch. We will fix the docs.
